// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/announcement.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AnnouncementReq struct {
	PageIndex            int64    `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageNum              int64    `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnouncementReq) Reset()         { *m = AnnouncementReq{} }
func (m *AnnouncementReq) String() string { return proto.CompactTextString(m) }
func (*AnnouncementReq) ProtoMessage()    {}
func (*AnnouncementReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce84847563ec99c2, []int{0}
}

func (m *AnnouncementReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnouncementReq.Unmarshal(m, b)
}
func (m *AnnouncementReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnouncementReq.Marshal(b, m, deterministic)
}
func (m *AnnouncementReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnouncementReq.Merge(m, src)
}
func (m *AnnouncementReq) XXX_Size() int {
	return xxx_messageInfo_AnnouncementReq.Size(m)
}
func (m *AnnouncementReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnouncementReq.DiscardUnknown(m)
}

var xxx_messageInfo_AnnouncementReq proto.InternalMessageInfo

func (m *AnnouncementReq) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *AnnouncementReq) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type AnnouncementResp struct {
	Status               *Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Announcements        []*Announcement `protobuf:"bytes,2,rep,name=announcements,proto3" json:"announcements,omitempty"`
	PageIndex            int64           `protobuf:"varint,3,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageNum              int64           `protobuf:"varint,4,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	Total                int64           `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AnnouncementResp) Reset()         { *m = AnnouncementResp{} }
func (m *AnnouncementResp) String() string { return proto.CompactTextString(m) }
func (*AnnouncementResp) ProtoMessage()    {}
func (*AnnouncementResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce84847563ec99c2, []int{1}
}

func (m *AnnouncementResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnouncementResp.Unmarshal(m, b)
}
func (m *AnnouncementResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnouncementResp.Marshal(b, m, deterministic)
}
func (m *AnnouncementResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnouncementResp.Merge(m, src)
}
func (m *AnnouncementResp) XXX_Size() int {
	return xxx_messageInfo_AnnouncementResp.Size(m)
}
func (m *AnnouncementResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnouncementResp.DiscardUnknown(m)
}

var xxx_messageInfo_AnnouncementResp proto.InternalMessageInfo

func (m *AnnouncementResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AnnouncementResp) GetAnnouncements() []*Announcement {
	if m != nil {
		return m.Announcements
	}
	return nil
}

func (m *AnnouncementResp) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *AnnouncementResp) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *AnnouncementResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AnnouncementDetailReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnouncementDetailReq) Reset()         { *m = AnnouncementDetailReq{} }
func (m *AnnouncementDetailReq) String() string { return proto.CompactTextString(m) }
func (*AnnouncementDetailReq) ProtoMessage()    {}
func (*AnnouncementDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce84847563ec99c2, []int{2}
}

func (m *AnnouncementDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnouncementDetailReq.Unmarshal(m, b)
}
func (m *AnnouncementDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnouncementDetailReq.Marshal(b, m, deterministic)
}
func (m *AnnouncementDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnouncementDetailReq.Merge(m, src)
}
func (m *AnnouncementDetailReq) XXX_Size() int {
	return xxx_messageInfo_AnnouncementDetailReq.Size(m)
}
func (m *AnnouncementDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnouncementDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_AnnouncementDetailReq proto.InternalMessageInfo

func (m *AnnouncementDetailReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AnnouncementDetailResp struct {
	Status               *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Announcement         *Announcement `protobuf:"bytes,2,opt,name=announcement,proto3" json:"announcement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AnnouncementDetailResp) Reset()         { *m = AnnouncementDetailResp{} }
func (m *AnnouncementDetailResp) String() string { return proto.CompactTextString(m) }
func (*AnnouncementDetailResp) ProtoMessage()    {}
func (*AnnouncementDetailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce84847563ec99c2, []int{3}
}

func (m *AnnouncementDetailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnouncementDetailResp.Unmarshal(m, b)
}
func (m *AnnouncementDetailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnouncementDetailResp.Marshal(b, m, deterministic)
}
func (m *AnnouncementDetailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnouncementDetailResp.Merge(m, src)
}
func (m *AnnouncementDetailResp) XXX_Size() int {
	return xxx_messageInfo_AnnouncementDetailResp.Size(m)
}
func (m *AnnouncementDetailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnouncementDetailResp.DiscardUnknown(m)
}

var xxx_messageInfo_AnnouncementDetailResp proto.InternalMessageInfo

func (m *AnnouncementDetailResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AnnouncementDetailResp) GetAnnouncement() *Announcement {
	if m != nil {
		return m.Announcement
	}
	return nil
}

func init() {
	proto.RegisterType((*AnnouncementReq)(nil), "protocol.AnnouncementReq")
	proto.RegisterType((*AnnouncementResp)(nil), "protocol.AnnouncementResp")
	proto.RegisterType((*AnnouncementDetailReq)(nil), "protocol.AnnouncementDetailReq")
	proto.RegisterType((*AnnouncementDetailResp)(nil), "protocol.AnnouncementDetailResp")
}

func init() { proto.RegisterFile("proto/announcement.proto", fileDescriptor_ce84847563ec99c2) }

var fileDescriptor_ce84847563ec99c2 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0xcd, 0x4b, 0x4e, 0xcd, 0x4d, 0xcd, 0x2b, 0xd1, 0x03,
	0x0b, 0x09, 0x71, 0x80, 0xa9, 0xe4, 0xfc, 0x1c, 0x29, 0x21, 0x88, 0x9a, 0xe4, 0xfc, 0xdc, 0xdc,
	0xfc, 0x3c, 0x88, 0x2c, 0x4c, 0xac, 0xb8, 0x24, 0xb1, 0xa4, 0xb4, 0x18, 0x22, 0xa6, 0xe4, 0xcd,
	0xc5, 0xef, 0x88, 0x64, 0x4e, 0x50, 0x6a, 0xa1, 0x90, 0x2c, 0x17, 0x57, 0x41, 0x62, 0x7a, 0x6a,
	0x7c, 0x66, 0x5e, 0x4a, 0x6a, 0x85, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x27, 0x48, 0xc4,
	0x13, 0x24, 0x20, 0x24, 0xc9, 0xc5, 0x01, 0x96, 0xce, 0x2b, 0xcd, 0x95, 0x60, 0x02, 0x4b, 0xb2,
	0x83, 0xf8, 0x7e, 0xa5, 0xb9, 0x4a, 0xa7, 0x18, 0xb9, 0x04, 0x50, 0x4d, 0x2b, 0x2e, 0x10, 0xd2,
	0xe0, 0x62, 0x83, 0xd8, 0x08, 0x36, 0x8a, 0xdb, 0x48, 0x40, 0x0f, 0xe6, 0x48, 0xbd, 0x60, 0xb0,
	0x78, 0x10, 0x54, 0x5e, 0xc8, 0x86, 0x8b, 0x17, 0xd9, 0x4f, 0xc5, 0x12, 0x4c, 0x0a, 0xcc, 0x1a,
	0xdc, 0x46, 0x62, 0x08, 0x0d, 0x28, 0x86, 0xa3, 0x2a, 0x46, 0x73, 0x36, 0x33, 0x3e, 0x67, 0xb3,
	0xa0, 0x38, 0x5b, 0x48, 0x84, 0x8b, 0xb5, 0x24, 0xbf, 0x24, 0x31, 0x47, 0x82, 0x15, 0x2c, 0x0e,
	0xe1, 0x28, 0xa9, 0x73, 0x89, 0x22, 0x5b, 0xe7, 0x92, 0x5a, 0x92, 0x98, 0x99, 0x03, 0x0a, 0x1f,
	0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x68, 0xb8, 0x30, 0x65, 0xa6, 0x28, 0xd5, 0x71, 0x89, 0x61, 0x53,
	0x48, 0x92, 0xd7, 0xad, 0xb8, 0x78, 0x90, 0x7d, 0x03, 0x0e, 0x58, 0xdc, 0x3e, 0x47, 0x51, 0xeb,
	0xc4, 0x1b, 0xc5, 0x9d, 0x9e, 0x6f, 0x0d, 0x53, 0x99, 0xc4, 0x06, 0x66, 0x19, 0x03, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x06, 0x03, 0xc9, 0x46, 0x26, 0x02, 0x00, 0x00,
}
