// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/file.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	FileId               string   `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4090a8107f0dd06, []int{0}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *File) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func init() {
	proto.RegisterType((*File)(nil), "protocol.File")
}

func init() { proto.RegisterFile("proto/file.proto", fileDescriptor_e4090a8107f0dd06) }

var fileDescriptor_e4090a8107f0dd06 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcb, 0xcc, 0x49, 0xd5, 0x03, 0x33, 0x85, 0x38, 0xc0, 0x54, 0x72, 0x7e, 0x8e,
	0x94, 0x10, 0x44, 0xae, 0xb8, 0x24, 0xb1, 0xa4, 0xb4, 0x18, 0x22, 0xab, 0xe4, 0xc9, 0xc5, 0xe2,
	0x96, 0x99, 0x93, 0x2a, 0xa4, 0xc1, 0xc5, 0x06, 0x11, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36,
	0x12, 0xd0, 0x83, 0x69, 0xd3, 0x0b, 0x06, 0x8b, 0x07, 0x41, 0xe5, 0x85, 0xc4, 0xb9, 0xd8, 0x41,
	0xa6, 0xc7, 0x67, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0xb1, 0x81, 0xb8, 0x9e, 0x29,
	0x4e, 0xc2, 0x51, 0x82, 0x30, 0x3d, 0xd6, 0x30, 0x46, 0x12, 0x1b, 0x98, 0x65, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x42, 0x26, 0x26, 0x46, 0x98, 0x00, 0x00, 0x00,
}
