// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/judge.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 判题目结果
type JudgeResult_Result int32

const (
	JudgeResult_SUCCESS                  JudgeResult_Result = 0
	JudgeResult_WRONG_ANSWER             JudgeResult_Result = -1
	JudgeResult_CPU_TIME_LIMIT_EXCEEDED  JudgeResult_Result = 1
	JudgeResult_REAL_TIME_LIMIT_EXCEEDED JudgeResult_Result = 2
	JudgeResult_MEMORY_LIMIT_EXCEEDED    JudgeResult_Result = 3
	JudgeResult_RUNTIME_ERROR            JudgeResult_Result = 4
	JudgeResult_SYSTEM_ERROR             JudgeResult_Result = 5
)

var JudgeResult_Result_name = map[int32]string{
	0:  "SUCCESS",
	-1: "WRONG_ANSWER",
	1:  "CPU_TIME_LIMIT_EXCEEDED",
	2:  "REAL_TIME_LIMIT_EXCEEDED",
	3:  "MEMORY_LIMIT_EXCEEDED",
	4:  "RUNTIME_ERROR",
	5:  "SYSTEM_ERROR",
}

var JudgeResult_Result_value = map[string]int32{
	"SUCCESS":                  0,
	"WRONG_ANSWER":             -1,
	"CPU_TIME_LIMIT_EXCEEDED":  1,
	"REAL_TIME_LIMIT_EXCEEDED": 2,
	"MEMORY_LIMIT_EXCEEDED":    3,
	"RUNTIME_ERROR":            4,
	"SYSTEM_ERROR":             5,
}

func (x JudgeResult_Result) String() string {
	return proto.EnumName(JudgeResult_Result_name, int32(x))
}

func (JudgeResult_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fc3ba8201c1ea690, []int{0, 0}
}

type JudgeResult struct {
	JudgeResult          JudgeResult_Result `protobuf:"varint,2,opt,name=judge_result,json=judgeResult,proto3,enum=protocol.JudgeResult_Result" json:"judge_result,omitempty"`
	CpuTime              int64              `protobuf:"varint,3,opt,name=cpu_time,json=cpuTime,proto3" json:"cpu_time,omitempty"`
	RealTime             int64              `protobuf:"varint,4,opt,name=real_time,json=realTime,proto3" json:"real_time,omitempty"`
	Memory               int64              `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Signal               int64              `protobuf:"varint,6,opt,name=signal,proto3" json:"signal,omitempty"`
	ExitCode             int64              `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *JudgeResult) Reset()         { *m = JudgeResult{} }
func (m *JudgeResult) String() string { return proto.CompactTextString(m) }
func (*JudgeResult) ProtoMessage()    {}
func (*JudgeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3ba8201c1ea690, []int{0}
}

func (m *JudgeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeResult.Unmarshal(m, b)
}
func (m *JudgeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeResult.Marshal(b, m, deterministic)
}
func (m *JudgeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeResult.Merge(m, src)
}
func (m *JudgeResult) XXX_Size() int {
	return xxx_messageInfo_JudgeResult.Size(m)
}
func (m *JudgeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeResult.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeResult proto.InternalMessageInfo

func (m *JudgeResult) GetJudgeResult() JudgeResult_Result {
	if m != nil {
		return m.JudgeResult
	}
	return JudgeResult_SUCCESS
}

func (m *JudgeResult) GetCpuTime() int64 {
	if m != nil {
		return m.CpuTime
	}
	return 0
}

func (m *JudgeResult) GetRealTime() int64 {
	if m != nil {
		return m.RealTime
	}
	return 0
}

func (m *JudgeResult) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *JudgeResult) GetSignal() int64 {
	if m != nil {
		return m.Signal
	}
	return 0
}

func (m *JudgeResult) GetExitCode() int64 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

type JudgeRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Src                  string   `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Language             int64    `protobuf:"varint,3,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeRequest) Reset()         { *m = JudgeRequest{} }
func (m *JudgeRequest) String() string { return proto.CompactTextString(m) }
func (*JudgeRequest) ProtoMessage()    {}
func (*JudgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3ba8201c1ea690, []int{1}
}

func (m *JudgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeRequest.Unmarshal(m, b)
}
func (m *JudgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeRequest.Marshal(b, m, deterministic)
}
func (m *JudgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeRequest.Merge(m, src)
}
func (m *JudgeRequest) XXX_Size() int {
	return xxx_messageInfo_JudgeRequest.Size(m)
}
func (m *JudgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeRequest proto.InternalMessageInfo

func (m *JudgeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JudgeRequest) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *JudgeRequest) GetLanguage() int64 {
	if m != nil {
		return m.Language
	}
	return 0
}

type JudgeResponse struct {
	Status               *Status        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Results              []*JudgeResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *JudgeResponse) Reset()         { *m = JudgeResponse{} }
func (m *JudgeResponse) String() string { return proto.CompactTextString(m) }
func (*JudgeResponse) ProtoMessage()    {}
func (*JudgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3ba8201c1ea690, []int{2}
}

func (m *JudgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeResponse.Unmarshal(m, b)
}
func (m *JudgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeResponse.Marshal(b, m, deterministic)
}
func (m *JudgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeResponse.Merge(m, src)
}
func (m *JudgeResponse) XXX_Size() int {
	return xxx_messageInfo_JudgeResponse.Size(m)
}
func (m *JudgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeResponse proto.InternalMessageInfo

func (m *JudgeResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *JudgeResponse) GetResults() []*JudgeResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.JudgeResult_Result", JudgeResult_Result_name, JudgeResult_Result_value)
	proto.RegisterType((*JudgeResult)(nil), "protocol.JudgeResult")
	proto.RegisterType((*JudgeRequest)(nil), "protocol.JudgeRequest")
	proto.RegisterType((*JudgeResponse)(nil), "protocol.JudgeResponse")
}

func init() { proto.RegisterFile("proto/judge.proto", fileDescriptor_fc3ba8201c1ea690) }

var fileDescriptor_fc3ba8201c1ea690 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x6f, 0x94, 0x40,
	0x14, 0xc6, 0x05, 0x5a, 0x96, 0x3e, 0x68, 0xc3, 0x8e, 0xa9, 0xce, 0xb6, 0x3d, 0x6c, 0x38, 0x71,
	0xa2, 0xc9, 0x7a, 0xf4, 0x60, 0x2a, 0x9d, 0x98, 0x35, 0xcb, 0xae, 0x19, 0xd8, 0xd4, 0x7a, 0x21,
	0x08, 0x13, 0xc2, 0x06, 0x16, 0x64, 0x20, 0xd1, 0xa3, 0x7f, 0x8f, 0x7f, 0xa4, 0x86, 0x19, 0xd0,
	0xc6, 0x94, 0xcb, 0xbc, 0xf7, 0xfd, 0xde, 0x7c, 0x61, 0xde, 0x07, 0xf3, 0xa6, 0xad, 0xbb, 0xfa,
	0xf6, 0xd0, 0x67, 0x39, 0xf3, 0x44, 0x8d, 0x0c, 0x71, 0xa4, 0x75, 0x79, 0x85, 0x24, 0xe4, 0x5d,
	0xd2, 0xf5, 0x5c, 0x52, 0xe7, 0xa7, 0x06, 0xe6, 0xc7, 0x61, 0x9a, 0x32, 0xde, 0x97, 0x1d, 0x7a,
	0x07, 0x96, 0xb8, 0x1c, 0xb7, 0xa2, 0xc7, 0xea, 0x52, 0x71, 0x2f, 0x56, 0x37, 0xde, 0x64, 0xe2,
	0x3d, 0x19, 0xf6, 0xe4, 0x41, 0xcd, 0xc3, 0x13, 0x83, 0x05, 0x18, 0x69, 0xd3, 0xc7, 0x5d, 0x51,
	0x31, 0xac, 0x2d, 0x15, 0x57, 0xa3, 0xb3, 0xb4, 0xe9, 0xa3, 0xa2, 0x62, 0xe8, 0x1a, 0xce, 0x5a,
	0x96, 0x94, 0x92, 0x9d, 0x08, 0x66, 0x0c, 0x82, 0x80, 0xaf, 0x40, 0xaf, 0x58, 0x55, 0xb7, 0x3f,
	0xf0, 0xa9, 0x20, 0x63, 0x37, 0xe8, 0xbc, 0xc8, 0x8f, 0x49, 0x89, 0x75, 0xa9, 0xcb, 0x6e, 0x30,
	0x63, 0xdf, 0x8b, 0x2e, 0x4e, 0xeb, 0x8c, 0xe1, 0x99, 0x34, 0x1b, 0x04, 0xbf, 0xce, 0x98, 0xf3,
	0x4b, 0x01, 0x7d, 0xfc, 0x1f, 0x13, 0x66, 0xe1, 0xde, 0xf7, 0x49, 0x18, 0xda, 0x2f, 0xd0, 0x02,
	0xac, 0x07, 0xba, 0xdb, 0x7e, 0x88, 0xef, 0xb6, 0xe1, 0x03, 0xa1, 0xf6, 0xef, 0xe9, 0x53, 0xd0,
	0x35, 0xbc, 0xf6, 0x3f, 0xed, 0xe3, 0x68, 0x1d, 0x90, 0x78, 0xb3, 0x0e, 0xd6, 0x51, 0x4c, 0x3e,
	0xfb, 0x84, 0xdc, 0x93, 0x7b, 0x5b, 0x41, 0x37, 0x80, 0x29, 0xb9, 0xdb, 0x3c, 0x4b, 0x55, 0xb4,
	0x80, 0xcb, 0x80, 0x04, 0x3b, 0xfa, 0xf8, 0x3f, 0xd2, 0xd0, 0x1c, 0xce, 0xe9, 0x7e, 0x2b, 0xae,
	0x11, 0x4a, 0x77, 0xd4, 0x3e, 0x41, 0x36, 0x58, 0xe1, 0x63, 0x18, 0x91, 0x60, 0x54, 0x4e, 0x9d,
	0x0d, 0x58, 0xe3, 0x56, 0xbf, 0xf5, 0x8c, 0x77, 0xe8, 0x02, 0xd4, 0x22, 0xc3, 0x8a, 0x78, 0x93,
	0x5a, 0x64, 0xc8, 0x06, 0x8d, 0xb7, 0xa9, 0x88, 0xe2, 0x8c, 0x0e, 0x25, 0xba, 0x02, 0xa3, 0x4c,
	0x8e, 0x79, 0x9f, 0xe4, 0xd3, 0x92, 0xff, 0xf6, 0xce, 0x01, 0xce, 0xa7, 0x8c, 0x9a, 0xfa, 0xc8,
	0x19, 0x72, 0x41, 0x97, 0x91, 0x0b, 0x4b, 0x73, 0x65, 0xff, 0x0b, 0x33, 0x14, 0x3a, 0x1d, 0x39,
	0xba, 0x85, 0x99, 0x8c, 0x9d, 0x63, 0x75, 0xa9, 0xb9, 0xe6, 0xea, 0xf2, 0xd9, 0xdc, 0xe9, 0x34,
	0xf5, 0xfe, 0xe5, 0x97, 0xf9, 0x34, 0xf0, 0x76, 0x2a, 0xbe, 0xea, 0xa2, 0x7a, 0xf3, 0x27, 0x00,
	0x00, 0xff, 0xff, 0xf3, 0x60, 0x53, 0x83, 0x8c, 0x02, 0x00, 0x00,
}
