// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/judge.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 判题目结果
type JudgeResult int32

const (
	JudgeResult_SUCCESS                  JudgeResult = 0
	JudgeResult_WRONG_ANSWER             JudgeResult = -1
	JudgeResult_CPU_TIME_LIMIT_EXCEEDED  JudgeResult = 1
	JudgeResult_REAL_TIME_LIMIT_EXCEEDED JudgeResult = 2
	JudgeResult_MEMORY_LIMIT_EXCEEDED    JudgeResult = 3
	JudgeResult_RUNTIME_ERROR            JudgeResult = 4
	JudgeResult_SYSTEM_ERROR             JudgeResult = 5
)

var JudgeResult_name = map[int32]string{
	0:  "SUCCESS",
	-1: "WRONG_ANSWER",
	1:  "CPU_TIME_LIMIT_EXCEEDED",
	2:  "REAL_TIME_LIMIT_EXCEEDED",
	3:  "MEMORY_LIMIT_EXCEEDED",
	4:  "RUNTIME_ERROR",
	5:  "SYSTEM_ERROR",
}

var JudgeResult_value = map[string]int32{
	"SUCCESS":                  0,
	"WRONG_ANSWER":             -1,
	"CPU_TIME_LIMIT_EXCEEDED":  1,
	"REAL_TIME_LIMIT_EXCEEDED": 2,
	"MEMORY_LIMIT_EXCEEDED":    3,
	"RUNTIME_ERROR":            4,
	"SYSTEM_ERROR":             5,
}

func (x JudgeResult) String() string {
	return proto.EnumName(JudgeResult_name, int32(x))
}

func (JudgeResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fc3ba8201c1ea690, []int{0}
}

// 判题语言
type Language int32

const (
	Language_C      Language = 0
	Language_C_PLUS Language = 1
	Language_PYTHON Language = 2
	Language_JAVA   Language = 3
)

var Language_name = map[int32]string{
	0: "C",
	1: "C_PLUS",
	2: "PYTHON",
	3: "JAVA",
}

var Language_value = map[string]int32{
	"C":      0,
	"C_PLUS": 1,
	"PYTHON": 2,
	"JAVA":   3,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}

func (Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fc3ba8201c1ea690, []int{1}
}

type JudgeRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Src                  string   `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Language             Language `protobuf:"varint,3,opt,name=language,proto3,enum=protocol.Language" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeRequest) Reset()         { *m = JudgeRequest{} }
func (m *JudgeRequest) String() string { return proto.CompactTextString(m) }
func (*JudgeRequest) ProtoMessage()    {}
func (*JudgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3ba8201c1ea690, []int{0}
}

func (m *JudgeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeRequest.Unmarshal(m, b)
}
func (m *JudgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeRequest.Marshal(b, m, deterministic)
}
func (m *JudgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeRequest.Merge(m, src)
}
func (m *JudgeRequest) XXX_Size() int {
	return xxx_messageInfo_JudgeRequest.Size(m)
}
func (m *JudgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeRequest proto.InternalMessageInfo

func (m *JudgeRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JudgeRequest) GetSrc() string {
	if m != nil {
		return m.Src
	}
	return ""
}

func (m *JudgeRequest) GetLanguage() Language {
	if m != nil {
		return m.Language
	}
	return Language_C
}

type JudgeResponse struct {
	Status               *Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	JudgeResult          JudgeResult `protobuf:"varint,2,opt,name=judge_result,json=judgeResult,proto3,enum=protocol.JudgeResult" json:"judge_result,omitempty"`
	CpuTime              int64       `protobuf:"varint,3,opt,name=cpu_time,json=cpuTime,proto3" json:"cpu_time,omitempty"`
	RealTime             int64       `protobuf:"varint,4,opt,name=real_time,json=realTime,proto3" json:"real_time,omitempty"`
	Memory               int64       `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	Signal               int64       `protobuf:"varint,6,opt,name=signal,proto3" json:"signal,omitempty"`
	ExitCode             int64       `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JudgeResponse) Reset()         { *m = JudgeResponse{} }
func (m *JudgeResponse) String() string { return proto.CompactTextString(m) }
func (*JudgeResponse) ProtoMessage()    {}
func (*JudgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc3ba8201c1ea690, []int{1}
}

func (m *JudgeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeResponse.Unmarshal(m, b)
}
func (m *JudgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeResponse.Marshal(b, m, deterministic)
}
func (m *JudgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeResponse.Merge(m, src)
}
func (m *JudgeResponse) XXX_Size() int {
	return xxx_messageInfo_JudgeResponse.Size(m)
}
func (m *JudgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeResponse proto.InternalMessageInfo

func (m *JudgeResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *JudgeResponse) GetJudgeResult() JudgeResult {
	if m != nil {
		return m.JudgeResult
	}
	return JudgeResult_SUCCESS
}

func (m *JudgeResponse) GetCpuTime() int64 {
	if m != nil {
		return m.CpuTime
	}
	return 0
}

func (m *JudgeResponse) GetRealTime() int64 {
	if m != nil {
		return m.RealTime
	}
	return 0
}

func (m *JudgeResponse) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *JudgeResponse) GetSignal() int64 {
	if m != nil {
		return m.Signal
	}
	return 0
}

func (m *JudgeResponse) GetExitCode() int64 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func init() {
	proto.RegisterEnum("protocol.JudgeResult", JudgeResult_name, JudgeResult_value)
	proto.RegisterEnum("protocol.Language", Language_name, Language_value)
	proto.RegisterType((*JudgeRequest)(nil), "protocol.JudgeRequest")
	proto.RegisterType((*JudgeResponse)(nil), "protocol.JudgeResponse")
}

func init() { proto.RegisterFile("proto/judge.proto", fileDescriptor_fc3ba8201c1ea690) }

var fileDescriptor_fc3ba8201c1ea690 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xbb, 0x76, 0xe2, 0xb8, 0x93, 0x34, 0xda, 0x0c, 0x2a, 0x38, 0x94, 0x43, 0xd4, 0x53,
	0xd4, 0x43, 0x90, 0xd2, 0x0b, 0x12, 0xa7, 0xe0, 0xae, 0x20, 0x55, 0x9c, 0x44, 0x6b, 0x87, 0x12,
	0x2e, 0xc6, 0xd8, 0xab, 0xc8, 0x95, 0x13, 0x07, 0xff, 0x91, 0xe0, 0x5b, 0xf1, 0xf1, 0xb8, 0x81,
	0xbc, 0x6b, 0x13, 0x84, 0xea, 0x8b, 0xdf, 0xbc, 0xdf, 0xec, 0xcc, 0x5b, 0x2d, 0x0c, 0x8e, 0x59,
	0x5a, 0xa4, 0xaf, 0x1f, 0xcb, 0x68, 0x27, 0x26, 0x52, 0xa3, 0x29, 0x7f, 0x61, 0x9a, 0xbc, 0x44,
	0x05, 0xf3, 0x22, 0x28, 0xca, 0x5c, 0xd1, 0xeb, 0x2f, 0xd0, 0xbb, 0xaf, 0x9a, 0xb9, 0xf8, 0x56,
	0x8a, 0xbc, 0xc0, 0x3e, 0x68, 0x71, 0x64, 0x91, 0x11, 0x19, 0xeb, 0x5c, 0x8b, 0x23, 0xa4, 0xa0,
	0xe7, 0x59, 0x68, 0x69, 0x23, 0x32, 0x3e, 0xe7, 0x95, 0xc4, 0x09, 0x98, 0x49, 0x70, 0xd8, 0x95,
	0xc1, 0x4e, 0x58, 0xfa, 0x88, 0x8c, 0xfb, 0x53, 0x9c, 0x34, 0x2b, 0x26, 0x8b, 0x9a, 0xf0, 0xbf,
	0x3d, 0xd7, 0xbf, 0x08, 0x5c, 0xd4, 0x2b, 0xf2, 0x63, 0x7a, 0xc8, 0x05, 0x8e, 0xc1, 0x50, 0x19,
	0xe4, 0x9e, 0xee, 0x94, 0x9e, 0xce, 0xbb, 0xd2, 0xe7, 0x35, 0xc7, 0x37, 0xd0, 0x93, 0x57, 0xf1,
	0x33, 0x91, 0x97, 0x49, 0x21, 0x63, 0xf4, 0xa7, 0x97, 0xa7, 0xfe, 0x66, 0x70, 0x99, 0x14, 0xbc,
	0xfb, 0x78, 0x2a, 0x70, 0x08, 0x66, 0x78, 0x2c, 0xfd, 0x22, 0xde, 0xab, 0x94, 0x3a, 0xef, 0x84,
	0xc7, 0xd2, 0x8b, 0xf7, 0x02, 0xaf, 0xe0, 0x3c, 0x13, 0x41, 0xa2, 0x58, 0x4b, 0x32, 0xb3, 0x32,
	0x24, 0x7c, 0x0e, 0xc6, 0x5e, 0xec, 0xd3, 0xec, 0x87, 0xd5, 0x96, 0xa4, 0xae, 0x2a, 0x3f, 0x8f,
	0x77, 0x87, 0x20, 0xb1, 0x0c, 0xe5, 0xab, 0xaa, 0x1a, 0x26, 0xbe, 0xc7, 0x85, 0x1f, 0xa6, 0x91,
	0xb0, 0x3a, 0x6a, 0x58, 0x65, 0xd8, 0x69, 0x24, 0x6e, 0x7e, 0x12, 0xe8, 0xfe, 0x93, 0x10, 0xbb,
	0xd0, 0x71, 0x37, 0xb6, 0xcd, 0x5c, 0x97, 0x9e, 0xe1, 0x10, 0x7a, 0x0f, 0x7c, 0xb5, 0x7c, 0xef,
	0xcf, 0x96, 0xee, 0x03, 0xe3, 0xf4, 0x77, 0xf3, 0x11, 0xbc, 0x82, 0x17, 0xf6, 0x7a, 0xe3, 0x7b,
	0x73, 0x87, 0xf9, 0x8b, 0xb9, 0x33, 0xf7, 0x7c, 0xf6, 0xc9, 0x66, 0xec, 0x8e, 0xdd, 0x51, 0x82,
	0xaf, 0xc0, 0xe2, 0x6c, 0xb6, 0x78, 0x92, 0x6a, 0x38, 0x84, 0x4b, 0x87, 0x39, 0x2b, 0xbe, 0xfd,
	0x1f, 0xe9, 0x38, 0x80, 0x0b, 0xbe, 0x59, 0xca, 0x63, 0x8c, 0xf3, 0x15, 0xa7, 0x2d, 0xa4, 0xd0,
	0x73, 0xb7, 0xae, 0xc7, 0x9c, 0xda, 0x69, 0xdf, 0xdc, 0x82, 0xd9, 0xbc, 0x21, 0xb6, 0x81, 0xd8,
	0xf4, 0x0c, 0x01, 0x0c, 0xdb, 0x5f, 0x2f, 0x36, 0x2e, 0x25, 0x95, 0x5e, 0x6f, 0xbd, 0x0f, 0xab,
	0x25, 0xd5, 0xd0, 0x84, 0xd6, 0xfd, 0xec, 0xe3, 0x8c, 0xea, 0xef, 0x9e, 0x7d, 0x1e, 0x34, 0x2f,
	0xf2, 0xb6, 0x11, 0x5f, 0x0d, 0xa9, 0x6e, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x58, 0xd9,
	0x8a, 0x93, 0x02, 0x00, 0x00,
}
