// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/login.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 登陆
type LoginReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=protocol.Code" json:"code,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_ok
}

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// 登出
type LogOutReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogOutReq) Reset()         { *m = LogOutReq{} }
func (m *LogOutReq) String() string { return proto.CompactTextString(m) }
func (*LogOutReq) ProtoMessage()    {}
func (*LogOutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{2}
}

func (m *LogOutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogOutReq.Unmarshal(m, b)
}
func (m *LogOutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogOutReq.Marshal(b, m, deterministic)
}
func (m *LogOutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogOutReq.Merge(m, src)
}
func (m *LogOutReq) XXX_Size() int {
	return xxx_messageInfo_LogOutReq.Size(m)
}
func (m *LogOutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogOutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogOutReq proto.InternalMessageInfo

func (m *LogOutReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type LogOutResp struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=protocol.Code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogOutResp) Reset()         { *m = LogOutResp{} }
func (m *LogOutResp) String() string { return proto.CompactTextString(m) }
func (*LogOutResp) ProtoMessage()    {}
func (*LogOutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{3}
}

func (m *LogOutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogOutResp.Unmarshal(m, b)
}
func (m *LogOutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogOutResp.Marshal(b, m, deterministic)
}
func (m *LogOutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogOutResp.Merge(m, src)
}
func (m *LogOutResp) XXX_Size() int {
	return xxx_messageInfo_LogOutResp.Size(m)
}
func (m *LogOutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogOutResp.DiscardUnknown(m)
}

var xxx_messageInfo_LogOutResp proto.InternalMessageInfo

func (m *LogOutResp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_ok
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "protocol.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "protocol.LoginResp")
	proto.RegisterType((*LogOutReq)(nil), "protocol.LogOutReq")
	proto.RegisterType((*LogOutResp)(nil), "protocol.LogOutResp")
}

func init() { proto.RegisterFile("proto/login.proto", fileDescriptor_b26af552c9148a54) }

var fileDescriptor_b26af552c9148a54 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xc9, 0x4f, 0xcf, 0xcc, 0xd3, 0x03, 0xb3, 0x85, 0x38, 0xc0, 0x54, 0x72, 0x7e,
	0x8e, 0x94, 0x00, 0x44, 0x32, 0x39, 0x3f, 0x25, 0x15, 0x22, 0xa7, 0xe4, 0xc4, 0xc5, 0xe1, 0x03,
	0x52, 0x1a, 0x94, 0x5a, 0x28, 0x24, 0xc5, 0xc5, 0x51, 0x5a, 0x9c, 0x5a, 0x94, 0x97, 0x98, 0x9b,
	0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe7, 0x83, 0xe4, 0x0a, 0x12, 0x8b, 0x8b, 0xcb,
	0xf3, 0x8b, 0x52, 0x24, 0x98, 0x20, 0x72, 0x30, 0xbe, 0x92, 0x2b, 0x17, 0x27, 0xd4, 0x8c, 0xe2,
	0x02, 0x21, 0x25, 0x2e, 0x16, 0x90, 0xf1, 0x60, 0x03, 0xf8, 0x8c, 0xf8, 0xf4, 0x60, 0x76, 0xeb,
	0x39, 0xe7, 0xa7, 0xa4, 0x06, 0x81, 0xe5, 0x84, 0x44, 0xb8, 0x58, 0x4b, 0xf2, 0xb3, 0x53, 0xf3,
	0xa0, 0x26, 0x41, 0x38, 0x4a, 0xea, 0x60, 0x63, 0xfc, 0x4b, 0x4b, 0x08, 0xb8, 0x45, 0xc9, 0x80,
	0x8b, 0x0b, 0xa6, 0x90, 0x38, 0x0b, 0x9d, 0x78, 0xa3, 0xb8, 0xd3, 0xf3, 0xad, 0x61, 0x32, 0x49,
	0x6c, 0x60, 0x96, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xd7, 0x78, 0xe3, 0x2c, 0x01, 0x00,
	0x00,
}
