// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/login.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 登陆 (post)
type RegisterReq struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IsSuccess            bool     `protobuf:"varint,2,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{1}
}

func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RegisterResp) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

// 登陆 (post)
type LoginReq struct {
	Account              string   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{2}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Status               *Status   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token                string    `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	User                 *UserInfo `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{3}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResp) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type LogoutResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResp) Reset()         { *m = LogoutResp{} }
func (m *LogoutResp) String() string { return proto.CompactTextString(m) }
func (*LogoutResp) ProtoMessage()    {}
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b26af552c9148a54, []int{4}
}

func (m *LogoutResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResp.Unmarshal(m, b)
}
func (m *LogoutResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResp.Marshal(b, m, deterministic)
}
func (m *LogoutResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResp.Merge(m, src)
}
func (m *LogoutResp) XXX_Size() int {
	return xxx_messageInfo_LogoutResp.Size(m)
}
func (m *LogoutResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResp.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResp proto.InternalMessageInfo

func (m *LogoutResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterReq)(nil), "protocol.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "protocol.RegisterResp")
	proto.RegisterType((*LoginReq)(nil), "protocol.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "protocol.LoginResp")
	proto.RegisterType((*LogoutResp)(nil), "protocol.LogoutResp")
}

func init() { proto.RegisterFile("proto/login.proto", fileDescriptor_b26af552c9148a54) }

var fileDescriptor_b26af552c9148a54 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x59, 0xab, 0x75, 0x77, 0xea, 0xc1, 0x46, 0x0f, 0x4b, 0x41, 0x28, 0x39, 0xc8, 0x9e,
	0x56, 0x50, 0xf4, 0xe2, 0x45, 0xbc, 0x09, 0x3d, 0xa5, 0x88, 0xe0, 0x45, 0xd6, 0x18, 0x97, 0x60,
	0x9b, 0x59, 0x33, 0x09, 0x7e, 0x7d, 0x69, 0xfe, 0xb4, 0xc7, 0xd2, 0xd3, 0xce, 0xbc, 0xdf, 0xbe,
	0x37, 0x93, 0x81, 0xe9, 0x60, 0xd1, 0xe1, 0xcd, 0x0a, 0x7b, 0x6d, 0xda, 0x50, 0xb3, 0x32, 0x7c,
	0x24, 0xae, 0x66, 0x2c, 0x42, 0x89, 0xeb, 0x35, 0x26, 0x9a, 0x35, 0x72, 0x9d, 0xf3, 0x14, 0x35,
	0x7e, 0x0f, 0x13, 0xa1, 0x7a, 0x4d, 0x4e, 0x59, 0xa1, 0x7e, 0xd9, 0x35, 0x1c, 0x7b, 0x52, 0xb6,
	0x2e, 0xe6, 0x45, 0x33, 0xb9, 0x65, 0x6d, 0xce, 0x6b, 0x5f, 0x49, 0xd9, 0x17, 0xf3, 0x8d, 0x22,
	0x70, 0xfe, 0x06, 0x67, 0x3b, 0x1b, 0x0d, 0xac, 0x81, 0x71, 0x8c, 0x4d, 0xce, 0xf3, 0x9d, 0x73,
	0x19, 0x74, 0x91, 0x38, 0xbb, 0x02, 0xd0, 0xf4, 0x41, 0x5e, 0x4a, 0x45, 0x54, 0x1f, 0xcd, 0x8b,
	0xa6, 0x14, 0x95, 0xa6, 0x65, 0x14, 0xf8, 0x13, 0x94, 0x8b, 0xcd, 0x83, 0x36, 0xcb, 0xd4, 0x70,
	0xda, 0x49, 0x89, 0xde, 0xb8, 0xf0, 0x5f, 0x25, 0x72, 0xcb, 0x66, 0x50, 0x0e, 0x1d, 0xd1, 0x1f,
	0xda, 0xaf, 0x7a, 0x14, 0xd0, 0xb6, 0xe7, 0x04, 0x55, 0x4a, 0x38, 0x68, 0xaf, 0x4b, 0x38, 0x71,
	0xf8, 0xa3, 0x4c, 0x1a, 0x15, 0x9b, 0xed, 0x3d, 0x46, 0x7b, 0xee, 0xf1, 0x00, 0xb0, 0xc0, 0x1e,
	0xbd, 0x3b, 0x6c, 0xea, 0xf3, 0xc5, 0xfb, 0x34, 0xa3, 0xc7, 0x5c, 0x7c, 0x8e, 0x43, 0x75, 0xf7,
	0x1f, 0x00, 0x00, 0xff, 0xff, 0x51, 0x46, 0xfb, 0x1e, 0xe1, 0x01, 0x00, 0x00,
}
