// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/match.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 创建比赛
type NewMatchReq struct {
	Paper                *Paper   `protobuf:"bytes,1,opt,name=paper,proto3" json:"paper,omitempty"`
	Match                *Match   `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMatchReq) Reset()         { *m = NewMatchReq{} }
func (m *NewMatchReq) String() string { return proto.CompactTextString(m) }
func (*NewMatchReq) ProtoMessage()    {}
func (*NewMatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{0}
}

func (m *NewMatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMatchReq.Unmarshal(m, b)
}
func (m *NewMatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMatchReq.Marshal(b, m, deterministic)
}
func (m *NewMatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMatchReq.Merge(m, src)
}
func (m *NewMatchReq) XXX_Size() int {
	return xxx_messageInfo_NewMatchReq.Size(m)
}
func (m *NewMatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_NewMatchReq proto.InternalMessageInfo

func (m *NewMatchReq) GetPaper() *Paper {
	if m != nil {
		return m.Paper
	}
	return nil
}

func (m *NewMatchReq) GetMatch() *Match {
	if m != nil {
		return m.Match
	}
	return nil
}

type NewMatchResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IsSuccess            bool     `protobuf:"varint,2,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMatchResp) Reset()         { *m = NewMatchResp{} }
func (m *NewMatchResp) String() string { return proto.CompactTextString(m) }
func (*NewMatchResp) ProtoMessage()    {}
func (*NewMatchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{1}
}

func (m *NewMatchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMatchResp.Unmarshal(m, b)
}
func (m *NewMatchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMatchResp.Marshal(b, m, deterministic)
}
func (m *NewMatchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMatchResp.Merge(m, src)
}
func (m *NewMatchResp) XXX_Size() int {
	return xxx_messageInfo_NewMatchResp.Size(m)
}
func (m *NewMatchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMatchResp.DiscardUnknown(m)
}

var xxx_messageInfo_NewMatchResp proto.InternalMessageInfo

func (m *NewMatchResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *NewMatchResp) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

// 拿到所有的比赛
type GetMatchesReq struct {
	PageIndex            int64    `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageNum              int64    `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchesReq) Reset()         { *m = GetMatchesReq{} }
func (m *GetMatchesReq) String() string { return proto.CompactTextString(m) }
func (*GetMatchesReq) ProtoMessage()    {}
func (*GetMatchesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{2}
}

func (m *GetMatchesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchesReq.Unmarshal(m, b)
}
func (m *GetMatchesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchesReq.Marshal(b, m, deterministic)
}
func (m *GetMatchesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchesReq.Merge(m, src)
}
func (m *GetMatchesReq) XXX_Size() int {
	return xxx_messageInfo_GetMatchesReq.Size(m)
}
func (m *GetMatchesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchesReq proto.InternalMessageInfo

func (m *GetMatchesReq) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *GetMatchesReq) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type GetMatchesResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PageIndex            int64    `protobuf:"varint,2,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageNum              int64    `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	Total                int64    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Matches              []*Match `protobuf:"bytes,5,rep,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchesResp) Reset()         { *m = GetMatchesResp{} }
func (m *GetMatchesResp) String() string { return proto.CompactTextString(m) }
func (*GetMatchesResp) ProtoMessage()    {}
func (*GetMatchesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{3}
}

func (m *GetMatchesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchesResp.Unmarshal(m, b)
}
func (m *GetMatchesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchesResp.Marshal(b, m, deterministic)
}
func (m *GetMatchesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchesResp.Merge(m, src)
}
func (m *GetMatchesResp) XXX_Size() int {
	return xxx_messageInfo_GetMatchesResp.Size(m)
}
func (m *GetMatchesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchesResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchesResp proto.InternalMessageInfo

func (m *GetMatchesResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetMatchesResp) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *GetMatchesResp) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *GetMatchesResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetMatchesResp) GetMatches() []*Match {
	if m != nil {
		return m.Matches
	}
	return nil
}

// 拿到所有的比赛
type GetMatchByIDReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchByIDReq) Reset()         { *m = GetMatchByIDReq{} }
func (m *GetMatchByIDReq) String() string { return proto.CompactTextString(m) }
func (*GetMatchByIDReq) ProtoMessage()    {}
func (*GetMatchByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{4}
}

func (m *GetMatchByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchByIDReq.Unmarshal(m, b)
}
func (m *GetMatchByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchByIDReq.Marshal(b, m, deterministic)
}
func (m *GetMatchByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchByIDReq.Merge(m, src)
}
func (m *GetMatchByIDReq) XXX_Size() int {
	return xxx_messageInfo_GetMatchByIDReq.Size(m)
}
func (m *GetMatchByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchByIDReq proto.InternalMessageInfo

func (m *GetMatchByIDReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetMatchByIDResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Match                *Match   `protobuf:"bytes,5,opt,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchByIDResp) Reset()         { *m = GetMatchByIDResp{} }
func (m *GetMatchByIDResp) String() string { return proto.CompactTextString(m) }
func (*GetMatchByIDResp) ProtoMessage()    {}
func (*GetMatchByIDResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{5}
}

func (m *GetMatchByIDResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchByIDResp.Unmarshal(m, b)
}
func (m *GetMatchByIDResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchByIDResp.Marshal(b, m, deterministic)
}
func (m *GetMatchByIDResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchByIDResp.Merge(m, src)
}
func (m *GetMatchByIDResp) XXX_Size() int {
	return xxx_messageInfo_GetMatchByIDResp.Size(m)
}
func (m *GetMatchByIDResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchByIDResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchByIDResp proto.InternalMessageInfo

func (m *GetMatchByIDResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetMatchByIDResp) GetMatch() *Match {
	if m != nil {
		return m.Match
	}
	return nil
}

// 获取比赛试卷
type GetPaperByIDReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaperByIDReq) Reset()         { *m = GetPaperByIDReq{} }
func (m *GetPaperByIDReq) String() string { return proto.CompactTextString(m) }
func (*GetPaperByIDReq) ProtoMessage()    {}
func (*GetPaperByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{6}
}

func (m *GetPaperByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaperByIDReq.Unmarshal(m, b)
}
func (m *GetPaperByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaperByIDReq.Marshal(b, m, deterministic)
}
func (m *GetPaperByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaperByIDReq.Merge(m, src)
}
func (m *GetPaperByIDReq) XXX_Size() int {
	return xxx_messageInfo_GetPaperByIDReq.Size(m)
}
func (m *GetPaperByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaperByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaperByIDReq proto.InternalMessageInfo

func (m *GetPaperByIDReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetPaperByIDResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Paper                *Paper   `protobuf:"bytes,2,opt,name=paper,proto3" json:"paper,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPaperByIDResp) Reset()         { *m = GetPaperByIDResp{} }
func (m *GetPaperByIDResp) String() string { return proto.CompactTextString(m) }
func (*GetPaperByIDResp) ProtoMessage()    {}
func (*GetPaperByIDResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{7}
}

func (m *GetPaperByIDResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPaperByIDResp.Unmarshal(m, b)
}
func (m *GetPaperByIDResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPaperByIDResp.Marshal(b, m, deterministic)
}
func (m *GetPaperByIDResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPaperByIDResp.Merge(m, src)
}
func (m *GetPaperByIDResp) XXX_Size() int {
	return xxx_messageInfo_GetPaperByIDResp.Size(m)
}
func (m *GetPaperByIDResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPaperByIDResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetPaperByIDResp proto.InternalMessageInfo

func (m *GetPaperByIDResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetPaperByIDResp) GetPaper() *Paper {
	if m != nil {
		return m.Paper
	}
	return nil
}

// 编辑比赛题目
type EditMatchReq struct {
	Match                *Match   `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditMatchReq) Reset()         { *m = EditMatchReq{} }
func (m *EditMatchReq) String() string { return proto.CompactTextString(m) }
func (*EditMatchReq) ProtoMessage()    {}
func (*EditMatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{8}
}

func (m *EditMatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMatchReq.Unmarshal(m, b)
}
func (m *EditMatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMatchReq.Marshal(b, m, deterministic)
}
func (m *EditMatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMatchReq.Merge(m, src)
}
func (m *EditMatchReq) XXX_Size() int {
	return xxx_messageInfo_EditMatchReq.Size(m)
}
func (m *EditMatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_EditMatchReq proto.InternalMessageInfo

func (m *EditMatchReq) GetMatch() *Match {
	if m != nil {
		return m.Match
	}
	return nil
}

type EditMatchResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IsSuccess            bool     `protobuf:"varint,2,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditMatchResp) Reset()         { *m = EditMatchResp{} }
func (m *EditMatchResp) String() string { return proto.CompactTextString(m) }
func (*EditMatchResp) ProtoMessage()    {}
func (*EditMatchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{9}
}

func (m *EditMatchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMatchResp.Unmarshal(m, b)
}
func (m *EditMatchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMatchResp.Marshal(b, m, deterministic)
}
func (m *EditMatchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMatchResp.Merge(m, src)
}
func (m *EditMatchResp) XXX_Size() int {
	return xxx_messageInfo_EditMatchResp.Size(m)
}
func (m *EditMatchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMatchResp.DiscardUnknown(m)
}

var xxx_messageInfo_EditMatchResp proto.InternalMessageInfo

func (m *EditMatchResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *EditMatchResp) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*NewMatchReq)(nil), "protocol.NewMatchReq")
	proto.RegisterType((*NewMatchResp)(nil), "protocol.NewMatchResp")
	proto.RegisterType((*GetMatchesReq)(nil), "protocol.GetMatchesReq")
	proto.RegisterType((*GetMatchesResp)(nil), "protocol.GetMatchesResp")
	proto.RegisterType((*GetMatchByIDReq)(nil), "protocol.GetMatchByIDReq")
	proto.RegisterType((*GetMatchByIDResp)(nil), "protocol.GetMatchByIDResp")
	proto.RegisterType((*GetPaperByIDReq)(nil), "protocol.GetPaperByIDReq")
	proto.RegisterType((*GetPaperByIDResp)(nil), "protocol.GetPaperByIDResp")
	proto.RegisterType((*EditMatchReq)(nil), "protocol.EditMatchReq")
	proto.RegisterType((*EditMatchResp)(nil), "protocol.EditMatchResp")
}

func init() { proto.RegisterFile("proto/match.proto", fileDescriptor_0aabbed45d0fc8b7) }

var fileDescriptor_0aabbed45d0fc8b7 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0x25, 0xc9, 0x2f, 0xfd, 0x33, 0xfd, 0xbf, 0x3f, 0x0f, 0x51, 0x28, 0xd4, 0x05, 0xa1, 0x5e,
	0x2a, 0x28, 0x9e, 0xbc, 0x15, 0x45, 0x7a, 0xb0, 0x48, 0x7a, 0x50, 0xf4, 0x50, 0x62, 0xb2, 0x68,
	0xa0, 0x69, 0x62, 0x77, 0x83, 0xfa, 0xc1, 0xfc, 0x7e, 0xb2, 0x33, 0x5d, 0x9b, 0x8a, 0x04, 0x0a,
	0x9e, 0x32, 0x79, 0x6f, 0xe6, 0xbd, 0xb7, 0xbb, 0x03, 0xbd, 0x6c, 0x95, 0xaa, 0xf4, 0x24, 0x09,
	0x54, 0xf8, 0x32, 0xc2, 0x9a, 0xd5, 0xf0, 0x13, 0xa6, 0x8b, 0x03, 0x46, 0x64, 0x98, 0x26, 0x49,
	0xba, 0x24, 0xd6, 0x60, 0x52, 0x05, 0x2a, 0x97, 0x84, 0xf1, 0x47, 0x68, 0x4c, 0xc5, 0xdb, 0x8d,
	0xd6, 0xf0, 0xc5, 0x2b, 0x3b, 0x02, 0x37, 0x0b, 0x32, 0xb1, 0xf2, 0xac, 0x81, 0x35, 0x6c, 0x9c,
	0x76, 0x46, 0x46, 0x70, 0x74, 0xab, 0x61, 0x9f, 0x58, 0xdd, 0x86, 0xb6, 0x9e, 0xfd, 0xb3, 0x8d,
	0x94, 0x88, 0xe5, 0x77, 0xd0, 0xdc, 0x88, 0xcb, 0x8c, 0x0d, 0xa1, 0x42, 0xe6, 0x6b, 0xf9, 0xee,
	0x66, 0x6e, 0x86, 0xb8, 0xbf, 0xe6, 0x59, 0x1f, 0x20, 0x96, 0x73, 0x99, 0x87, 0xa1, 0x90, 0x12,
	0x5d, 0x6a, 0x7e, 0x3d, 0x96, 0x33, 0x02, 0xf8, 0x04, 0x5a, 0xd7, 0x42, 0xa1, 0xb0, 0x90, 0x3a,
	0x77, 0x1f, 0x20, 0x0b, 0x9e, 0xc5, 0x3c, 0x5e, 0x46, 0xe2, 0x1d, 0xd5, 0x1d, 0xbf, 0xae, 0x91,
	0x89, 0x06, 0xd8, 0x3e, 0xd4, 0x90, 0x5e, 0xe6, 0x09, 0x8a, 0x39, 0x7e, 0x55, 0xff, 0x4f, 0xf3,
	0x84, 0x7f, 0x5a, 0xd0, 0x2e, 0x6a, 0xed, 0x1a, 0xb3, 0x60, 0x6b, 0x97, 0xd9, 0x3a, 0x5b, 0xb6,
	0x6c, 0x0f, 0x5c, 0x95, 0xaa, 0x60, 0xe1, 0xfd, 0x43, 0x9c, 0x7e, 0xd8, 0x31, 0x54, 0x13, 0x0a,
	0xe2, 0xb9, 0x03, 0xe7, 0xb7, 0x9b, 0x35, 0x3c, 0x3f, 0x84, 0x8e, 0x89, 0x3d, 0xfe, 0x98, 0x5c,
	0xea, 0x4b, 0x68, 0x83, 0x1d, 0x47, 0xeb, 0xc3, 0xdb, 0x71, 0xc4, 0x43, 0xe8, 0x6e, 0xb7, 0xec,
	0x74, 0xb6, 0xef, 0x37, 0x76, 0x4b, 0xdf, 0x98, 0x72, 0xe0, 0x76, 0x94, 0xe7, 0x28, 0xb4, 0xec,
	0x9a, 0x83, 0x56, 0xd2, 0x2e, 0x5b, 0x49, 0x7e, 0x0e, 0xcd, 0xab, 0x28, 0x56, 0xc5, 0x4d, 0xa6,
	0xf8, 0x56, 0x69, 0xfc, 0x7b, 0x68, 0x15, 0xc6, 0xfe, 0x70, 0x47, 0xc7, 0xff, 0x1f, 0x7a, 0x66,
	0xf2, 0xc2, 0x14, 0x4f, 0x15, 0xac, 0xce, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x05, 0xb8,
	0xac, 0xbc, 0x03, 0x00, 0x00,
}
