// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/match.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Paper : 试卷
type Paper struct {
	Id       int64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Problems []*Problem `protobuf:"bytes,2,rep,name=problems,proto3" json:"problems,omitempty"`
	// 组卷的参数
	Difficulty           int64    `protobuf:"varint,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	ProblemNum           int64    `protobuf:"varint,4,opt,name=problem_num,json=problemNum,proto3" json:"problem_num,omitempty"`
	KnowledgePoints      []int64  `protobuf:"varint,5,rep,packed,name=knowledge_points,json=knowledgePoints,proto3" json:"knowledge_points,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paper) Reset()         { *m = Paper{} }
func (m *Paper) String() string { return proto.CompactTextString(m) }
func (*Paper) ProtoMessage()    {}
func (*Paper) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{0}
}

func (m *Paper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paper.Unmarshal(m, b)
}
func (m *Paper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paper.Marshal(b, m, deterministic)
}
func (m *Paper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paper.Merge(m, src)
}
func (m *Paper) XXX_Size() int {
	return xxx_messageInfo_Paper.Size(m)
}
func (m *Paper) XXX_DiscardUnknown() {
	xxx_messageInfo_Paper.DiscardUnknown(m)
}

var xxx_messageInfo_Paper proto.InternalMessageInfo

func (m *Paper) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Paper) GetProblems() []*Problem {
	if m != nil {
		return m.Problems
	}
	return nil
}

func (m *Paper) GetDifficulty() int64 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *Paper) GetProblemNum() int64 {
	if m != nil {
		return m.ProblemNum
	}
	return 0
}

func (m *Paper) GetKnowledgePoints() []int64 {
	if m != nil {
		return m.KnowledgePoints
	}
	return nil
}

// Match : 比赛
type Match struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsPublic             bool     `protobuf:"varint,2,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration             int64    `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	IsOver               bool     `protobuf:"varint,5,opt,name=is_over,json=isOver,proto3" json:"is_over,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Intriduction         string   `protobuf:"bytes,7,opt,name=intriduction,proto3" json:"intriduction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Match) Reset()         { *m = Match{} }
func (m *Match) String() string { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()    {}
func (*Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{1}
}

func (m *Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Match.Unmarshal(m, b)
}
func (m *Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Match.Marshal(b, m, deterministic)
}
func (m *Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Match.Merge(m, src)
}
func (m *Match) XXX_Size() int {
	return xxx_messageInfo_Match.Size(m)
}
func (m *Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Match proto.InternalMessageInfo

func (m *Match) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Match) GetIsPublic() bool {
	if m != nil {
		return m.IsPublic
	}
	return false
}

func (m *Match) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Match) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Match) GetIsOver() bool {
	if m != nil {
		return m.IsOver
	}
	return false
}

func (m *Match) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Match) GetIntriduction() string {
	if m != nil {
		return m.Intriduction
	}
	return ""
}

// 创建比赛
type NewMatchReq struct {
	Paper                *Paper   `protobuf:"bytes,1,opt,name=paper,proto3" json:"paper,omitempty"`
	Match                *Match   `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMatchReq) Reset()         { *m = NewMatchReq{} }
func (m *NewMatchReq) String() string { return proto.CompactTextString(m) }
func (*NewMatchReq) ProtoMessage()    {}
func (*NewMatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{2}
}

func (m *NewMatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMatchReq.Unmarshal(m, b)
}
func (m *NewMatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMatchReq.Marshal(b, m, deterministic)
}
func (m *NewMatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMatchReq.Merge(m, src)
}
func (m *NewMatchReq) XXX_Size() int {
	return xxx_messageInfo_NewMatchReq.Size(m)
}
func (m *NewMatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_NewMatchReq proto.InternalMessageInfo

func (m *NewMatchReq) GetPaper() *Paper {
	if m != nil {
		return m.Paper
	}
	return nil
}

func (m *NewMatchReq) GetMatch() *Match {
	if m != nil {
		return m.Match
	}
	return nil
}

type NewMatchResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Result               bool     `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewMatchResp) Reset()         { *m = NewMatchResp{} }
func (m *NewMatchResp) String() string { return proto.CompactTextString(m) }
func (*NewMatchResp) ProtoMessage()    {}
func (*NewMatchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{3}
}

func (m *NewMatchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMatchResp.Unmarshal(m, b)
}
func (m *NewMatchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMatchResp.Marshal(b, m, deterministic)
}
func (m *NewMatchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMatchResp.Merge(m, src)
}
func (m *NewMatchResp) XXX_Size() int {
	return xxx_messageInfo_NewMatchResp.Size(m)
}
func (m *NewMatchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMatchResp.DiscardUnknown(m)
}

var xxx_messageInfo_NewMatchResp proto.InternalMessageInfo

func (m *NewMatchResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *NewMatchResp) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// 拿到所有的比赛
type GetMatchesReq struct {
	PageIndex            int64    `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageNum              int64    `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchesReq) Reset()         { *m = GetMatchesReq{} }
func (m *GetMatchesReq) String() string { return proto.CompactTextString(m) }
func (*GetMatchesReq) ProtoMessage()    {}
func (*GetMatchesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{4}
}

func (m *GetMatchesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchesReq.Unmarshal(m, b)
}
func (m *GetMatchesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchesReq.Marshal(b, m, deterministic)
}
func (m *GetMatchesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchesReq.Merge(m, src)
}
func (m *GetMatchesReq) XXX_Size() int {
	return xxx_messageInfo_GetMatchesReq.Size(m)
}
func (m *GetMatchesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchesReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchesReq proto.InternalMessageInfo

func (m *GetMatchesReq) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *GetMatchesReq) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type GetMatchesResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PageIndex            int64    `protobuf:"varint,2,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageNum              int64    `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	Total                int64    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Matches              []*Match `protobuf:"bytes,5,rep,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchesResp) Reset()         { *m = GetMatchesResp{} }
func (m *GetMatchesResp) String() string { return proto.CompactTextString(m) }
func (*GetMatchesResp) ProtoMessage()    {}
func (*GetMatchesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{5}
}

func (m *GetMatchesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchesResp.Unmarshal(m, b)
}
func (m *GetMatchesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchesResp.Marshal(b, m, deterministic)
}
func (m *GetMatchesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchesResp.Merge(m, src)
}
func (m *GetMatchesResp) XXX_Size() int {
	return xxx_messageInfo_GetMatchesResp.Size(m)
}
func (m *GetMatchesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchesResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchesResp proto.InternalMessageInfo

func (m *GetMatchesResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetMatchesResp) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *GetMatchesResp) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *GetMatchesResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *GetMatchesResp) GetMatches() []*Match {
	if m != nil {
		return m.Matches
	}
	return nil
}

// 拿到所有的比赛
type GetMatchByIDReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchByIDReq) Reset()         { *m = GetMatchByIDReq{} }
func (m *GetMatchByIDReq) String() string { return proto.CompactTextString(m) }
func (*GetMatchByIDReq) ProtoMessage()    {}
func (*GetMatchByIDReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{6}
}

func (m *GetMatchByIDReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchByIDReq.Unmarshal(m, b)
}
func (m *GetMatchByIDReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchByIDReq.Marshal(b, m, deterministic)
}
func (m *GetMatchByIDReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchByIDReq.Merge(m, src)
}
func (m *GetMatchByIDReq) XXX_Size() int {
	return xxx_messageInfo_GetMatchByIDReq.Size(m)
}
func (m *GetMatchByIDReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchByIDReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchByIDReq proto.InternalMessageInfo

func (m *GetMatchByIDReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetMatchByIDResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Match                *Match   `protobuf:"bytes,5,opt,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchByIDResp) Reset()         { *m = GetMatchByIDResp{} }
func (m *GetMatchByIDResp) String() string { return proto.CompactTextString(m) }
func (*GetMatchByIDResp) ProtoMessage()    {}
func (*GetMatchByIDResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{7}
}

func (m *GetMatchByIDResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchByIDResp.Unmarshal(m, b)
}
func (m *GetMatchByIDResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchByIDResp.Marshal(b, m, deterministic)
}
func (m *GetMatchByIDResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchByIDResp.Merge(m, src)
}
func (m *GetMatchByIDResp) XXX_Size() int {
	return xxx_messageInfo_GetMatchByIDResp.Size(m)
}
func (m *GetMatchByIDResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchByIDResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchByIDResp proto.InternalMessageInfo

func (m *GetMatchByIDResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetMatchByIDResp) GetMatch() *Match {
	if m != nil {
		return m.Match
	}
	return nil
}

// 获取比赛试卷
type GetMatchPaperReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchPaperReq) Reset()         { *m = GetMatchPaperReq{} }
func (m *GetMatchPaperReq) String() string { return proto.CompactTextString(m) }
func (*GetMatchPaperReq) ProtoMessage()    {}
func (*GetMatchPaperReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{8}
}

func (m *GetMatchPaperReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchPaperReq.Unmarshal(m, b)
}
func (m *GetMatchPaperReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchPaperReq.Marshal(b, m, deterministic)
}
func (m *GetMatchPaperReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchPaperReq.Merge(m, src)
}
func (m *GetMatchPaperReq) XXX_Size() int {
	return xxx_messageInfo_GetMatchPaperReq.Size(m)
}
func (m *GetMatchPaperReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchPaperReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchPaperReq proto.InternalMessageInfo

func (m *GetMatchPaperReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetMatchPaperResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Paper                *Paper   `protobuf:"bytes,2,opt,name=paper,proto3" json:"paper,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMatchPaperResp) Reset()         { *m = GetMatchPaperResp{} }
func (m *GetMatchPaperResp) String() string { return proto.CompactTextString(m) }
func (*GetMatchPaperResp) ProtoMessage()    {}
func (*GetMatchPaperResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{9}
}

func (m *GetMatchPaperResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMatchPaperResp.Unmarshal(m, b)
}
func (m *GetMatchPaperResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMatchPaperResp.Marshal(b, m, deterministic)
}
func (m *GetMatchPaperResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMatchPaperResp.Merge(m, src)
}
func (m *GetMatchPaperResp) XXX_Size() int {
	return xxx_messageInfo_GetMatchPaperResp.Size(m)
}
func (m *GetMatchPaperResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMatchPaperResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetMatchPaperResp proto.InternalMessageInfo

func (m *GetMatchPaperResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetMatchPaperResp) GetPaper() *Paper {
	if m != nil {
		return m.Paper
	}
	return nil
}

// 编辑比赛题目
type EditMatchReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Match                *Match   `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditMatchReq) Reset()         { *m = EditMatchReq{} }
func (m *EditMatchReq) String() string { return proto.CompactTextString(m) }
func (*EditMatchReq) ProtoMessage()    {}
func (*EditMatchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{10}
}

func (m *EditMatchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMatchReq.Unmarshal(m, b)
}
func (m *EditMatchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMatchReq.Marshal(b, m, deterministic)
}
func (m *EditMatchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMatchReq.Merge(m, src)
}
func (m *EditMatchReq) XXX_Size() int {
	return xxx_messageInfo_EditMatchReq.Size(m)
}
func (m *EditMatchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMatchReq.DiscardUnknown(m)
}

var xxx_messageInfo_EditMatchReq proto.InternalMessageInfo

func (m *EditMatchReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditMatchReq) GetMatch() *Match {
	if m != nil {
		return m.Match
	}
	return nil
}

type EditMatchResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IsOk                 bool     `protobuf:"varint,2,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditMatchResp) Reset()         { *m = EditMatchResp{} }
func (m *EditMatchResp) String() string { return proto.CompactTextString(m) }
func (*EditMatchResp) ProtoMessage()    {}
func (*EditMatchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{11}
}

func (m *EditMatchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditMatchResp.Unmarshal(m, b)
}
func (m *EditMatchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditMatchResp.Marshal(b, m, deterministic)
}
func (m *EditMatchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditMatchResp.Merge(m, src)
}
func (m *EditMatchResp) XXX_Size() int {
	return xxx_messageInfo_EditMatchResp.Size(m)
}
func (m *EditMatchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EditMatchResp.DiscardUnknown(m)
}

var xxx_messageInfo_EditMatchResp proto.InternalMessageInfo

func (m *EditMatchResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *EditMatchResp) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

func init() {
	proto.RegisterType((*Paper)(nil), "protocol.Paper")
	proto.RegisterType((*Match)(nil), "protocol.Match")
	proto.RegisterType((*NewMatchReq)(nil), "protocol.NewMatchReq")
	proto.RegisterType((*NewMatchResp)(nil), "protocol.NewMatchResp")
	proto.RegisterType((*GetMatchesReq)(nil), "protocol.GetMatchesReq")
	proto.RegisterType((*GetMatchesResp)(nil), "protocol.GetMatchesResp")
	proto.RegisterType((*GetMatchByIDReq)(nil), "protocol.GetMatchByIDReq")
	proto.RegisterType((*GetMatchByIDResp)(nil), "protocol.GetMatchByIDResp")
	proto.RegisterType((*GetMatchPaperReq)(nil), "protocol.GetMatchPaperReq")
	proto.RegisterType((*GetMatchPaperResp)(nil), "protocol.GetMatchPaperResp")
	proto.RegisterType((*EditMatchReq)(nil), "protocol.EditMatchReq")
	proto.RegisterType((*EditMatchResp)(nil), "protocol.EditMatchResp")
}

func init() { proto.RegisterFile("proto/match.proto", fileDescriptor_0aabbed45d0fc8b7) }

var fileDescriptor_0aabbed45d0fc8b7 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x95, 0xed, 0x3a, 0x8f, 0x9b, 0xa6, 0x49, 0x06, 0x04, 0xa6, 0xa8, 0x10, 0x46, 0x42, 0x72,
	0x17, 0x04, 0xa9, 0x2c, 0xd9, 0x55, 0x54, 0x28, 0x0b, 0xd2, 0xc8, 0xb0, 0x82, 0x85, 0xe5, 0xd8,
	0xd3, 0x30, 0x8a, 0xc7, 0x63, 0x3c, 0xe3, 0x96, 0xfe, 0x16, 0x12, 0x7b, 0x3e, 0x0d, 0xcd, 0x23,
	0x4f, 0xaa, 0x88, 0xac, 0x3c, 0xf7, 0x9c, 0xeb, 0x33, 0xe7, 0x3e, 0x06, 0x06, 0x65, 0xc5, 0x25,
	0x7f, 0xcb, 0x12, 0x99, 0x7e, 0x1f, 0xe9, 0x33, 0x6a, 0xe9, 0x4f, 0xca, 0xf3, 0x53, 0x64, 0xc8,
	0x94, 0x33, 0xc6, 0x0b, 0xc3, 0x2e, 0x31, 0x21, 0x13, 0x59, 0x0b, 0x83, 0xe1, 0x5f, 0x0e, 0xf8,
	0xd3, 0xa4, 0x24, 0x15, 0x3a, 0x01, 0x97, 0x66, 0x81, 0x33, 0x74, 0x42, 0x2f, 0x72, 0x69, 0x86,
	0xde, 0x80, 0x52, 0x9b, 0xe5, 0x84, 0x89, 0xc0, 0x1d, 0x7a, 0x61, 0xe7, 0x62, 0x30, 0x5a, 0xca,
	0x8f, 0xa6, 0x86, 0x89, 0x56, 0x29, 0xe8, 0x05, 0x40, 0x46, 0x6f, 0x6e, 0x68, 0x5a, 0xe7, 0xf2,
	0x3e, 0xf0, 0xb4, 0xcc, 0x06, 0x82, 0x5e, 0x42, 0xc7, 0xe6, 0xc6, 0x45, 0xcd, 0x82, 0x23, 0x93,
	0x60, 0xa1, 0x49, 0xcd, 0xd0, 0x39, 0xf4, 0x17, 0x05, 0xbf, 0xcb, 0x49, 0x36, 0x27, 0x71, 0xc9,
	0x69, 0x21, 0x45, 0xe0, 0x0f, 0xbd, 0xd0, 0x8b, 0x7a, 0x2b, 0x7c, 0xaa, 0x61, 0xfc, 0xc7, 0x01,
	0xff, 0x93, 0x2a, 0xfb, 0x1f, 0xd3, 0xcf, 0xa1, 0x4d, 0x45, 0x5c, 0xd6, 0xb3, 0x9c, 0xa6, 0x81,
	0x3b, 0x74, 0xc2, 0x56, 0xd4, 0xa2, 0x62, 0xaa, 0x63, 0x74, 0x06, 0x20, 0x64, 0x52, 0xc9, 0x58,
	0x52, 0x46, 0xac, 0xc5, 0xb6, 0x46, 0xbe, 0x50, 0x46, 0xd0, 0x29, 0xb4, 0xb2, 0xba, 0x4a, 0x24,
	0xe5, 0x85, 0xb5, 0xb7, 0x8a, 0xd1, 0x53, 0x68, 0x52, 0x11, 0xf3, 0x5b, 0x52, 0x05, 0xbe, 0x56,
	0x6d, 0x50, 0x71, 0x7d, 0x4b, 0x2a, 0x84, 0xe0, 0xa8, 0x48, 0x18, 0x09, 0x1a, 0x43, 0x27, 0x6c,
	0x47, 0xfa, 0x8c, 0x30, 0x1c, 0xd3, 0x42, 0x56, 0x34, 0xab, 0x53, 0x2d, 0xd6, 0xd4, 0xdc, 0x16,
	0x86, 0xbf, 0x41, 0x67, 0x42, 0xee, 0x74, 0x11, 0x11, 0xf9, 0x81, 0x5e, 0x83, 0x5f, 0xaa, 0x29,
	0xe8, 0x52, 0x3a, 0x17, 0xbd, 0x8d, 0x4e, 0x2b, 0x38, 0x32, 0xac, 0x4a, 0xd3, 0xe3, 0xd6, 0xa5,
	0x6d, 0xa5, 0x19, 0x25, 0xc3, 0xe2, 0x29, 0x1c, 0xaf, 0xc5, 0x45, 0x89, 0x42, 0x68, 0x98, 0xa1,
	0x5b, 0xf9, 0xfe, 0xfa, 0xbf, 0xcf, 0x1a, 0x8f, 0x2c, 0x8f, 0x9e, 0x40, 0xa3, 0x22, 0xa2, 0xce,
	0xa5, 0x6d, 0x9e, 0x8d, 0xf0, 0x18, 0xba, 0x1f, 0x89, 0xd4, 0x8a, 0x44, 0x28, 0xc3, 0x67, 0x00,
	0x65, 0x32, 0x27, 0x31, 0x2d, 0x32, 0xf2, 0xd3, 0x0e, 0xa0, 0xad, 0x90, 0xb1, 0x02, 0xd0, 0x33,
	0x68, 0x69, 0x5a, 0x8d, 0xda, 0xd5, 0x64, 0x53, 0xc5, 0x93, 0x9a, 0xe1, 0xdf, 0x0e, 0x9c, 0x6c,
	0x6a, 0x1d, 0xe4, 0x6f, 0xfb, 0x5a, 0x77, 0xdf, 0xb5, 0xde, 0xd6, 0xb5, 0xe8, 0x31, 0xf8, 0x92,
	0xcb, 0x24, 0xb7, 0xa3, 0x35, 0x01, 0x3a, 0x87, 0x26, 0x33, 0x46, 0xf4, 0xae, 0x3d, 0xd0, 0xd2,
	0x25, 0x8f, 0x5f, 0x41, 0x6f, 0x69, 0xfb, 0xf2, 0x7e, 0xfc, 0x41, 0x35, 0x61, 0x67, 0xfb, 0x70,
	0x0a, 0xfd, 0xed, 0x94, 0x83, 0x6a, 0x5b, 0x0d, 0xd7, 0xdf, 0x3b, 0x5c, 0xbc, 0xbe, 0xc4, 0xec,
	0xc6, 0x03, 0x46, 0x32, 0x18, 0xec, 0xe4, 0x1c, 0xea, 0xc4, 0x6c, 0xa3, 0xbb, 0x6f, 0x1b, 0xf1,
	0x15, 0x1c, 0x5f, 0x65, 0x54, 0xae, 0x96, 0x78, 0xf7, 0x31, 0xfe, 0xe7, 0xb6, 0x4e, 0xa0, 0xbb,
	0x21, 0x73, 0x90, 0xd1, 0x47, 0xe0, 0xab, 0x67, 0xb9, 0xb0, 0xdb, 0x7a, 0x44, 0xc5, 0xf5, 0xe2,
	0xb2, 0xfb, 0xb5, 0x33, 0xe7, 0xef, 0x97, 0xbf, 0xcc, 0x1a, 0xfa, 0xf4, 0xee, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc6, 0x82, 0x8b, 0xd5, 0x2f, 0x05, 0x00, 0x00,
}
