// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/problem.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 题目分类列表（get）
type ProblemList struct {
	Categories           []string   `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	Problems             []*Problem `protobuf:"bytes,2,rep,name=problems,proto3" json:"problems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProblemList) Reset()         { *m = ProblemList{} }
func (m *ProblemList) String() string { return proto.CompactTextString(m) }
func (*ProblemList) ProtoMessage()    {}
func (*ProblemList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d735835d0407c35c, []int{0}
}

func (m *ProblemList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemList.Unmarshal(m, b)
}
func (m *ProblemList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemList.Marshal(b, m, deterministic)
}
func (m *ProblemList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemList.Merge(m, src)
}
func (m *ProblemList) XXX_Size() int {
	return xxx_messageInfo_ProblemList.Size(m)
}
func (m *ProblemList) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemList.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemList proto.InternalMessageInfo

func (m *ProblemList) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *ProblemList) GetProblems() []*Problem {
	if m != nil {
		return m.Problems
	}
	return nil
}

func init() {
	proto.RegisterType((*ProblemList)(nil), "protocol.ProblemList")
}

func init() { proto.RegisterFile("proto/problem.proto", fileDescriptor_d735835d0407c35c) }

var fileDescriptor_d735835d0407c35c = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x28, 0xca, 0x4f, 0xca, 0x49, 0xcd, 0xd5, 0x03, 0xf3, 0x84, 0x38, 0xc0, 0x54,
	0x72, 0x7e, 0x8e, 0x94, 0x10, 0x44, 0x3a, 0x39, 0x3f, 0x37, 0x37, 0x3f, 0x0f, 0x22, 0xab, 0x14,
	0xc3, 0xc5, 0x1d, 0x00, 0x51, 0xee, 0x93, 0x59, 0x5c, 0x22, 0x24, 0xc7, 0xc5, 0x95, 0x9c, 0x58,
	0x92, 0x9a, 0x9e, 0x5f, 0x94, 0x99, 0x5a, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x19, 0x84, 0x24,
	0x22, 0xa4, 0xcb, 0xc5, 0x01, 0x35, 0xbd, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x50,
	0x0f, 0x66, 0xbe, 0x1e, 0xd4, 0xa0, 0x20, 0xb8, 0x12, 0x27, 0xde, 0x28, 0xee, 0xf4, 0x7c, 0x6b,
	0x98, 0x82, 0x24, 0x36, 0x30, 0xcb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x88, 0x43, 0x26, 0x71,
	0xa8, 0x00, 0x00, 0x00,
}
