// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rank.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RankListReq struct {
	PageIndex            int64    `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageNum              int64    `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankListReq) Reset()         { *m = RankListReq{} }
func (m *RankListReq) String() string { return proto.CompactTextString(m) }
func (*RankListReq) ProtoMessage()    {}
func (*RankListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c4dbbb5cfa23ee, []int{0}
}

func (m *RankListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankListReq.Unmarshal(m, b)
}
func (m *RankListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankListReq.Marshal(b, m, deterministic)
}
func (m *RankListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankListReq.Merge(m, src)
}
func (m *RankListReq) XXX_Size() int {
	return xxx_messageInfo_RankListReq.Size(m)
}
func (m *RankListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RankListReq.DiscardUnknown(m)
}

var xxx_messageInfo_RankListReq proto.InternalMessageInfo

func (m *RankListReq) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *RankListReq) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type RankListResp struct {
	Status               *Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RankItems            []*RankItem `protobuf:"bytes,2,rep,name=rank_items,json=rankItems,proto3" json:"rank_items,omitempty"`
	PageIndex            int64       `protobuf:"varint,3,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageNum              int64       `protobuf:"varint,4,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	Total                int64       `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	Pos                  int64       `protobuf:"varint,6,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RankListResp) Reset()         { *m = RankListResp{} }
func (m *RankListResp) String() string { return proto.CompactTextString(m) }
func (*RankListResp) ProtoMessage()    {}
func (*RankListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c4dbbb5cfa23ee, []int{1}
}

func (m *RankListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankListResp.Unmarshal(m, b)
}
func (m *RankListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankListResp.Marshal(b, m, deterministic)
}
func (m *RankListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankListResp.Merge(m, src)
}
func (m *RankListResp) XXX_Size() int {
	return xxx_messageInfo_RankListResp.Size(m)
}
func (m *RankListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RankListResp.DiscardUnknown(m)
}

var xxx_messageInfo_RankListResp proto.InternalMessageInfo

func (m *RankListResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *RankListResp) GetRankItems() []*RankItem {
	if m != nil {
		return m.RankItems
	}
	return nil
}

func (m *RankListResp) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *RankListResp) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *RankListResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *RankListResp) GetPos() int64 {
	if m != nil {
		return m.Pos
	}
	return 0
}

func init() {
	proto.RegisterType((*RankListReq)(nil), "protocol.RankListReq")
	proto.RegisterType((*RankListResp)(nil), "protocol.RankListResp")
}

func init() { proto.RegisterFile("proto/rank.proto", fileDescriptor_12c4dbbb5cfa23ee) }

var fileDescriptor_12c4dbbb5cfa23ee = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0x63, 0x63, 0x3b, 0x51, 0x08, 0x83, 0x87, 0x55, 0x10, 0x4a, 0x4f, 0x39, 0x45,
	0xac, 0x47, 0x6f, 0x5e, 0xa4, 0x20, 0x1e, 0xd6, 0x9b, 0x97, 0xb2, 0xd6, 0xa5, 0x84, 0x76, 0x3f,
	0xcc, 0x4e, 0xc0, 0x3f, 0xe9, 0x7f, 0x92, 0x9d, 0x6d, 0x08, 0x7a, 0xe8, 0x69, 0xdf, 0x79, 0xde,
	0x65, 0xf6, 0x59, 0xa8, 0x7c, 0xe7, 0xc8, 0xdd, 0x75, 0xca, 0xee, 0x1b, 0x8e, 0x38, 0xe3, 0x63,
	0xeb, 0x0e, 0x37, 0x98, 0xba, 0xad, 0x33, 0xc6, 0xd9, 0xd4, 0x0e, 0x2c, 0x90, 0xa2, 0x3e, 0x24,
	0xb6, 0x7c, 0x86, 0x52, 0x2a, 0xbb, 0x7f, 0x69, 0x03, 0x49, 0xfd, 0x85, 0xb7, 0x00, 0x5e, 0xed,
	0xf4, 0xa6, 0xb5, 0x9f, 0xfa, 0x5b, 0x64, 0x8b, 0xac, 0xce, 0xe5, 0x3c, 0x92, 0x75, 0x04, 0x78,
	0x0d, 0x33, 0xae, 0x6d, 0x6f, 0xc4, 0x84, 0xcb, 0xf3, 0x38, 0xbf, 0xf6, 0x66, 0xf9, 0x93, 0xc1,
	0xc5, 0xb8, 0x29, 0x78, 0xac, 0xa1, 0x48, 0x2f, 0xf1, 0x9a, 0x72, 0x55, 0x35, 0x83, 0x5c, 0xf3,
	0xc6, 0x5c, 0x1e, 0x7b, 0xbc, 0x07, 0x88, 0x7f, 0xd8, 0xb4, 0xa4, 0x4d, 0x10, 0x93, 0x45, 0x5e,
	0x97, 0x2b, 0x1c, 0x6f, 0xc7, 0xad, 0x6b, 0xd2, 0x46, 0xce, 0xbb, 0x63, 0x0a, 0xff, 0x3c, 0xf3,
	0x53, 0x9e, 0x67, 0x7f, 0x3c, 0xf1, 0x0a, 0xa6, 0xe4, 0x48, 0x1d, 0xc4, 0x94, 0x79, 0x1a, 0xb0,
	0x82, 0xdc, 0xbb, 0x20, 0x0a, 0x66, 0x31, 0x3e, 0x5d, 0xbe, 0x97, 0x3b, 0xf7, 0x38, 0x48, 0x7c,
	0x14, 0x9c, 0x1e, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xea, 0x17, 0x30, 0x93, 0x74, 0x01, 0x00,
	0x00,
}
