// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/tag.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 获取所有tag
type GetTagsReq struct {
	PageIndex            int64    `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageNum              int64    `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTagsReq) Reset()         { *m = GetTagsReq{} }
func (m *GetTagsReq) String() string { return proto.CompactTextString(m) }
func (*GetTagsReq) ProtoMessage()    {}
func (*GetTagsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc6f15189f1be6, []int{0}
}

func (m *GetTagsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagsReq.Unmarshal(m, b)
}
func (m *GetTagsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagsReq.Marshal(b, m, deterministic)
}
func (m *GetTagsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagsReq.Merge(m, src)
}
func (m *GetTagsReq) XXX_Size() int {
	return xxx_messageInfo_GetTagsReq.Size(m)
}
func (m *GetTagsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagsReq proto.InternalMessageInfo

func (m *GetTagsReq) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *GetTagsReq) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

type GetTagsResp struct {
	Status               *Status          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Tags                 map[int64]string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PageIndex            int64            `protobuf:"varint,3,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageNum              int64            `protobuf:"varint,4,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	Total                int64            `protobuf:"varint,5,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetTagsResp) Reset()         { *m = GetTagsResp{} }
func (m *GetTagsResp) String() string { return proto.CompactTextString(m) }
func (*GetTagsResp) ProtoMessage()    {}
func (*GetTagsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc6f15189f1be6, []int{1}
}

func (m *GetTagsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTagsResp.Unmarshal(m, b)
}
func (m *GetTagsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTagsResp.Marshal(b, m, deterministic)
}
func (m *GetTagsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTagsResp.Merge(m, src)
}
func (m *GetTagsResp) XXX_Size() int {
	return xxx_messageInfo_GetTagsResp.Size(m)
}
func (m *GetTagsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTagsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetTagsResp proto.InternalMessageInfo

func (m *GetTagsResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetTagsResp) GetTags() map[int64]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *GetTagsResp) GetPageIndex() int64 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *GetTagsResp) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *GetTagsResp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

// 新增Tag
type AddTagReq struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagReq) Reset()         { *m = AddTagReq{} }
func (m *AddTagReq) String() string { return proto.CompactTextString(m) }
func (*AddTagReq) ProtoMessage()    {}
func (*AddTagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc6f15189f1be6, []int{2}
}

func (m *AddTagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagReq.Unmarshal(m, b)
}
func (m *AddTagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagReq.Marshal(b, m, deterministic)
}
func (m *AddTagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagReq.Merge(m, src)
}
func (m *AddTagReq) XXX_Size() int {
	return xxx_messageInfo_AddTagReq.Size(m)
}
func (m *AddTagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagReq proto.InternalMessageInfo

func (m *AddTagReq) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type AddTagResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IsSuccess            bool     `protobuf:"varint,2,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagResp) Reset()         { *m = AddTagResp{} }
func (m *AddTagResp) String() string { return proto.CompactTextString(m) }
func (*AddTagResp) ProtoMessage()    {}
func (*AddTagResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc6f15189f1be6, []int{3}
}

func (m *AddTagResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagResp.Unmarshal(m, b)
}
func (m *AddTagResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagResp.Marshal(b, m, deterministic)
}
func (m *AddTagResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagResp.Merge(m, src)
}
func (m *AddTagResp) XXX_Size() int {
	return xxx_messageInfo_AddTagResp.Size(m)
}
func (m *AddTagResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagResp proto.InternalMessageInfo

func (m *AddTagResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AddTagResp) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

// 修改tag
type UpdateTagReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTagReq) Reset()         { *m = UpdateTagReq{} }
func (m *UpdateTagReq) String() string { return proto.CompactTextString(m) }
func (*UpdateTagReq) ProtoMessage()    {}
func (*UpdateTagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc6f15189f1be6, []int{4}
}

func (m *UpdateTagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTagReq.Unmarshal(m, b)
}
func (m *UpdateTagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTagReq.Marshal(b, m, deterministic)
}
func (m *UpdateTagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTagReq.Merge(m, src)
}
func (m *UpdateTagReq) XXX_Size() int {
	return xxx_messageInfo_UpdateTagReq.Size(m)
}
func (m *UpdateTagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTagReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTagReq proto.InternalMessageInfo

func (m *UpdateTagReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTagReq) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type UpdateTagResp struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	IsSuccess            bool     `protobuf:"varint,2,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTagResp) Reset()         { *m = UpdateTagResp{} }
func (m *UpdateTagResp) String() string { return proto.CompactTextString(m) }
func (*UpdateTagResp) ProtoMessage()    {}
func (*UpdateTagResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc6f15189f1be6, []int{5}
}

func (m *UpdateTagResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTagResp.Unmarshal(m, b)
}
func (m *UpdateTagResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTagResp.Marshal(b, m, deterministic)
}
func (m *UpdateTagResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTagResp.Merge(m, src)
}
func (m *UpdateTagResp) XXX_Size() int {
	return xxx_messageInfo_UpdateTagResp.Size(m)
}
func (m *UpdateTagResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTagResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTagResp proto.InternalMessageInfo

func (m *UpdateTagResp) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *UpdateTagResp) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*GetTagsReq)(nil), "protocol.GetTagsReq")
	proto.RegisterType((*GetTagsResp)(nil), "protocol.GetTagsResp")
	proto.RegisterMapType((map[int64]string)(nil), "protocol.GetTagsResp.TagsEntry")
	proto.RegisterType((*AddTagReq)(nil), "protocol.AddTagReq")
	proto.RegisterType((*AddTagResp)(nil), "protocol.AddTagResp")
	proto.RegisterType((*UpdateTagReq)(nil), "protocol.UpdateTagReq")
	proto.RegisterType((*UpdateTagResp)(nil), "protocol.UpdateTagResp")
}

func init() { proto.RegisterFile("proto/tag.proto", fileDescriptor_48dc6f15189f1be6) }

var fileDescriptor_48dc6f15189f1be6 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0xc1, 0x4f, 0x32, 0x31,
	0x10, 0xc5, 0xb3, 0xbb, 0xc0, 0x47, 0x87, 0x4f, 0xc5, 0xea, 0x61, 0x25, 0x21, 0x92, 0x3d, 0x71,
	0x5a, 0x0d, 0x1c, 0x34, 0x7a, 0xd2, 0x44, 0x8d, 0x17, 0x0f, 0x05, 0x12, 0xe3, 0x85, 0x54, 0xda,
	0x34, 0x1b, 0x61, 0x77, 0xa5, 0x5d, 0x23, 0x7f, 0xb8, 0x77, 0xd3, 0xe9, 0x2e, 0xa0, 0x07, 0x13,
	0x13, 0x4f, 0x7d, 0xf3, 0x5e, 0x67, 0xe6, 0xd7, 0xc2, 0x5e, 0xbe, 0xcc, 0x4c, 0x76, 0x62, 0xb8,
	0x8a, 0x51, 0xd1, 0x26, 0x1e, 0xb3, 0x6c, 0xde, 0xa1, 0x2e, 0xd2, 0x86, 0x9b, 0x42, 0xbb, 0x34,
	0xba, 0x05, 0xb8, 0x93, 0x66, 0xcc, 0x95, 0x66, 0xf2, 0x95, 0x76, 0x01, 0x72, 0xae, 0xe4, 0x34,
	0x49, 0x85, 0x7c, 0x0f, 0xbd, 0x9e, 0xd7, 0x0f, 0x18, 0xb1, 0xce, 0xbd, 0x35, 0xe8, 0x11, 0x34,
	0x31, 0x4e, 0x8b, 0x45, 0xe8, 0x63, 0xf8, 0xcf, 0xd6, 0x0f, 0xc5, 0x22, 0xfa, 0xf0, 0xa0, 0xb5,
	0x1e, 0xa4, 0x73, 0xda, 0x87, 0x86, 0xdb, 0x83, 0x53, 0x5a, 0x83, 0x76, 0x5c, 0x61, 0xc4, 0x23,
	0xf4, 0x59, 0x99, 0xd3, 0x21, 0xd4, 0x0c, 0x57, 0x3a, 0xf4, 0x7b, 0x41, 0xbf, 0x35, 0x38, 0xde,
	0xdc, 0xdb, 0x1a, 0x17, 0x5b, 0x71, 0x93, 0x9a, 0xe5, 0x8a, 0xe1, 0xe5, 0x6f, 0xa0, 0xc1, 0x4f,
	0xa0, 0xb5, 0x2f, 0xa0, 0xf4, 0x10, 0xea, 0x26, 0x33, 0x7c, 0x1e, 0xd6, 0xd1, 0x77, 0x45, 0xe7,
	0x0c, 0xc8, 0x7a, 0x05, 0x6d, 0x43, 0xf0, 0x22, 0x57, 0xe5, 0xf3, 0xad, 0xb4, 0x4d, 0x6f, 0x7c,
	0x5e, 0x48, 0x7c, 0x35, 0x61, 0xae, 0xb8, 0xf0, 0xcf, 0xbd, 0xa8, 0x0b, 0xe4, 0x4a, 0x88, 0x31,
	0x57, 0xf6, 0xfb, 0xda, 0x10, 0x18, 0xae, 0xb0, 0x91, 0x30, 0x2b, 0xa3, 0x09, 0x40, 0x15, 0xff,
	0xea, 0x53, 0xba, 0x00, 0x89, 0x9e, 0xea, 0x62, 0x36, 0x93, 0x5a, 0xe3, 0xd6, 0x26, 0x23, 0x89,
	0x1e, 0x39, 0x23, 0x3a, 0x85, 0xff, 0x93, 0x5c, 0x70, 0x23, 0xcb, 0xc5, 0xbb, 0xe0, 0x27, 0xa2,
	0x04, 0xf6, 0x13, 0x51, 0x81, 0xf8, 0x1b, 0x90, 0x47, 0xd8, 0xd9, 0xea, 0xf8, 0x43, 0x96, 0xeb,
	0x83, 0xa7, 0xfd, 0xaa, 0xf3, 0xb2, 0x12, 0xcf, 0x0d, 0x54, 0xc3, 0xcf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc4, 0x3a, 0x9f, 0xcb, 0x8e, 0x02, 0x00, 0x00,
}
