// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user_manage.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 批量获取用户信息
type GetUsersReq struct {
	Role                 Role     `protobuf:"varint,1,opt,name=role,proto3,enum=protocol.Role" json:"role,omitempty"`
	GetAll               bool     `protobuf:"varint,2,opt,name=get_all,json=getAll,proto3" json:"get_all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersReq) Reset()         { *m = GetUsersReq{} }
func (m *GetUsersReq) String() string { return proto.CompactTextString(m) }
func (*GetUsersReq) ProtoMessage()    {}
func (*GetUsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_79107de06ed33a41, []int{0}
}

func (m *GetUsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersReq.Unmarshal(m, b)
}
func (m *GetUsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersReq.Marshal(b, m, deterministic)
}
func (m *GetUsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersReq.Merge(m, src)
}
func (m *GetUsersReq) XXX_Size() int {
	return xxx_messageInfo_GetUsersReq.Size(m)
}
func (m *GetUsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersReq proto.InternalMessageInfo

func (m *GetUsersReq) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_STUDENT
}

func (m *GetUsersReq) GetGetAll() bool {
	if m != nil {
		return m.GetAll
	}
	return false
}

type GetUsersResp struct {
	Code                 Code        `protobuf:"varint,1,opt,name=code,proto3,enum=protocol.Code" json:"code,omitempty"`
	Users                []*UserInfo `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetUsersResp) Reset()         { *m = GetUsersResp{} }
func (m *GetUsersResp) String() string { return proto.CompactTextString(m) }
func (*GetUsersResp) ProtoMessage()    {}
func (*GetUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_79107de06ed33a41, []int{1}
}

func (m *GetUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResp.Unmarshal(m, b)
}
func (m *GetUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResp.Marshal(b, m, deterministic)
}
func (m *GetUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResp.Merge(m, src)
}
func (m *GetUsersResp) XXX_Size() int {
	return xxx_messageInfo_GetUsersResp.Size(m)
}
func (m *GetUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResp proto.InternalMessageInfo

func (m *GetUsersResp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_OK
}

func (m *GetUsersResp) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

// 批量增加用户
type AddUsersReq struct {
	Users                []*UserInfo `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddUsersReq) Reset()         { *m = AddUsersReq{} }
func (m *AddUsersReq) String() string { return proto.CompactTextString(m) }
func (*AddUsersReq) ProtoMessage()    {}
func (*AddUsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_79107de06ed33a41, []int{2}
}

func (m *AddUsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUsersReq.Unmarshal(m, b)
}
func (m *AddUsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUsersReq.Marshal(b, m, deterministic)
}
func (m *AddUsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUsersReq.Merge(m, src)
}
func (m *AddUsersReq) XXX_Size() int {
	return xxx_messageInfo_AddUsersReq.Size(m)
}
func (m *AddUsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUsersReq proto.InternalMessageInfo

func (m *AddUsersReq) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

type AddUsersResp struct {
	Code                 Code        `protobuf:"varint,1,opt,name=code,proto3,enum=protocol.Code" json:"code,omitempty"`
	Succeed              []*UserInfo `protobuf:"bytes,2,rep,name=succeed,proto3" json:"succeed,omitempty"`
	Fail                 []*UserInfo `protobuf:"bytes,3,rep,name=fail,proto3" json:"fail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddUsersResp) Reset()         { *m = AddUsersResp{} }
func (m *AddUsersResp) String() string { return proto.CompactTextString(m) }
func (*AddUsersResp) ProtoMessage()    {}
func (*AddUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_79107de06ed33a41, []int{3}
}

func (m *AddUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUsersResp.Unmarshal(m, b)
}
func (m *AddUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUsersResp.Marshal(b, m, deterministic)
}
func (m *AddUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUsersResp.Merge(m, src)
}
func (m *AddUsersResp) XXX_Size() int {
	return xxx_messageInfo_AddUsersResp.Size(m)
}
func (m *AddUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddUsersResp proto.InternalMessageInfo

func (m *AddUsersResp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_OK
}

func (m *AddUsersResp) GetSucceed() []*UserInfo {
	if m != nil {
		return m.Succeed
	}
	return nil
}

func (m *AddUsersResp) GetFail() []*UserInfo {
	if m != nil {
		return m.Fail
	}
	return nil
}

// 批量修改用户
type UpdateUsersReq struct {
	User                 []*UserInfo `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateUsersReq) Reset()         { *m = UpdateUsersReq{} }
func (m *UpdateUsersReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUsersReq) ProtoMessage()    {}
func (*UpdateUsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_79107de06ed33a41, []int{4}
}

func (m *UpdateUsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUsersReq.Unmarshal(m, b)
}
func (m *UpdateUsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUsersReq.Marshal(b, m, deterministic)
}
func (m *UpdateUsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUsersReq.Merge(m, src)
}
func (m *UpdateUsersReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUsersReq.Size(m)
}
func (m *UpdateUsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUsersReq proto.InternalMessageInfo

func (m *UpdateUsersReq) GetUser() []*UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUsersResp struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=protocol.Code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUsersResp) Reset()         { *m = UpdateUsersResp{} }
func (m *UpdateUsersResp) String() string { return proto.CompactTextString(m) }
func (*UpdateUsersResp) ProtoMessage()    {}
func (*UpdateUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_79107de06ed33a41, []int{5}
}

func (m *UpdateUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUsersResp.Unmarshal(m, b)
}
func (m *UpdateUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUsersResp.Marshal(b, m, deterministic)
}
func (m *UpdateUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUsersResp.Merge(m, src)
}
func (m *UpdateUsersResp) XXX_Size() int {
	return xxx_messageInfo_UpdateUsersResp.Size(m)
}
func (m *UpdateUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUsersResp proto.InternalMessageInfo

func (m *UpdateUsersResp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_OK
}

// 批量删除用户
type DelUsersReq struct {
	User                 []*UserInfo `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DelUsersReq) Reset()         { *m = DelUsersReq{} }
func (m *DelUsersReq) String() string { return proto.CompactTextString(m) }
func (*DelUsersReq) ProtoMessage()    {}
func (*DelUsersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_79107de06ed33a41, []int{6}
}

func (m *DelUsersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUsersReq.Unmarshal(m, b)
}
func (m *DelUsersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUsersReq.Marshal(b, m, deterministic)
}
func (m *DelUsersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUsersReq.Merge(m, src)
}
func (m *DelUsersReq) XXX_Size() int {
	return xxx_messageInfo_DelUsersReq.Size(m)
}
func (m *DelUsersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUsersReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelUsersReq proto.InternalMessageInfo

func (m *DelUsersReq) GetUser() []*UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type DelUsersResp struct {
	Code                 Code     `protobuf:"varint,1,opt,name=code,proto3,enum=protocol.Code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelUsersResp) Reset()         { *m = DelUsersResp{} }
func (m *DelUsersResp) String() string { return proto.CompactTextString(m) }
func (*DelUsersResp) ProtoMessage()    {}
func (*DelUsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_79107de06ed33a41, []int{7}
}

func (m *DelUsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelUsersResp.Unmarshal(m, b)
}
func (m *DelUsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelUsersResp.Marshal(b, m, deterministic)
}
func (m *DelUsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelUsersResp.Merge(m, src)
}
func (m *DelUsersResp) XXX_Size() int {
	return xxx_messageInfo_DelUsersResp.Size(m)
}
func (m *DelUsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelUsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelUsersResp proto.InternalMessageInfo

func (m *DelUsersResp) GetCode() Code {
	if m != nil {
		return m.Code
	}
	return Code_OK
}

func init() {
	proto.RegisterType((*GetUsersReq)(nil), "protocol.GetUsersReq")
	proto.RegisterType((*GetUsersResp)(nil), "protocol.GetUsersResp")
	proto.RegisterType((*AddUsersReq)(nil), "protocol.AddUsersReq")
	proto.RegisterType((*AddUsersResp)(nil), "protocol.AddUsersResp")
	proto.RegisterType((*UpdateUsersReq)(nil), "protocol.UpdateUsersReq")
	proto.RegisterType((*UpdateUsersResp)(nil), "protocol.UpdateUsersResp")
	proto.RegisterType((*DelUsersReq)(nil), "protocol.DelUsersReq")
	proto.RegisterType((*DelUsersResp)(nil), "protocol.DelUsersResp")
}

func init() { proto.RegisterFile("proto/user_manage.proto", fileDescriptor_79107de06ed33a41) }

var fileDescriptor_79107de06ed33a41 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x4f, 0x4f, 0x4b, 0xc3, 0x30,
	0x14, 0xa7, 0x5b, 0xdd, 0xc6, 0x6b, 0xad, 0x92, 0xcb, 0xca, 0x4e, 0x25, 0x87, 0xd1, 0x83, 0x54,
	0xa8, 0x0c, 0x05, 0x4f, 0x53, 0x41, 0xf4, 0x18, 0xd8, 0x45, 0x84, 0x51, 0x9b, 0xb7, 0x22, 0xa4,
	0x4d, 0x6d, 0xba, 0xef, 0xe0, 0xc7, 0x96, 0xa4, 0xb6, 0x45, 0xc4, 0xd9, 0x9d, 0x12, 0xde, 0xef,
	0x3f, 0xcc, 0xcb, 0x4a, 0xd6, 0xf2, 0x72, 0xaf, 0xb0, 0xda, 0xe6, 0x49, 0x91, 0x64, 0x18, 0x99,
	0x0b, 0x99, 0x99, 0x27, 0x95, 0x62, 0x71, 0xde, 0x50, 0x52, 0xc9, 0xbf, 0xb1, 0x05, 0x69, 0x2f,
	0x79, 0x2e, 0x8b, 0xe6, 0x46, 0x9f, 0xc1, 0x79, 0xc4, 0x7a, 0xa3, 0xb0, 0x52, 0x0c, 0x3f, 0x08,
	0x05, 0xbb, 0x92, 0x02, 0x7d, 0x2b, 0xb0, 0x42, 0x2f, 0xf6, 0xa2, 0xd6, 0x2d, 0x62, 0x52, 0x20,
	0x33, 0x18, 0x99, 0xc3, 0x34, 0xc3, 0x7a, 0x9b, 0x08, 0xe1, 0x8f, 0x02, 0x2b, 0x9c, 0xb1, 0x49,
	0x86, 0xf5, 0x5a, 0x08, 0xfa, 0x0a, 0x6e, 0xef, 0xa5, 0x4a, 0x6d, 0xa6, 0xd3, 0x7f, 0x9b, 0xdd,
	0x4b, 0x8e, 0xcc, 0x60, 0x24, 0x84, 0x13, 0x3d, 0x42, 0xf9, 0xa3, 0x60, 0x1c, 0x3a, 0x31, 0xe9,
	0x49, 0xda, 0xe7, 0xa9, 0xd8, 0x49, 0xd6, 0x10, 0xe8, 0x35, 0x38, 0x6b, 0xce, 0xbb, 0xa6, 0x9d,
	0xd0, 0xfa, 0x4f, 0xf8, 0x69, 0x81, 0xdb, 0x2b, 0x07, 0xf6, 0xba, 0x80, 0xa9, 0xda, 0xa7, 0x29,
	0x22, 0x3f, 0xd0, 0xac, 0xa5, 0x90, 0x25, 0xd8, 0xbb, 0xe4, 0x5d, 0xf8, 0xe3, 0x3f, 0xa9, 0x06,
	0xa7, 0x37, 0xe0, 0x6d, 0x4a, 0x9e, 0xd4, 0xd8, 0xcd, 0x58, 0x82, 0xad, 0x5b, 0x1e, 0x58, 0x61,
	0x70, 0xba, 0x82, 0xb3, 0x1f, 0xca, 0x61, 0x33, 0xe8, 0x0a, 0x9c, 0x07, 0x14, 0x47, 0xa7, 0xc5,
	0xe0, 0xf6, 0xb2, 0x61, 0x51, 0x77, 0xa7, 0x2f, 0x4e, 0x26, 0x6f, 0x5b, 0xe4, 0x6d, 0x62, 0x7e,
	0x57, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x90, 0x19, 0xd6, 0x36, 0xaa, 0x02, 0x00, 0x00,
}
